// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetApiGateway
    {
        /// <summary>
        /// Get information about a Yandex Cloud API Gateway. For more information, see the official documentation [Yandex Cloud API Gateway](https://cloud.yandex.com/docs/api-gateway/).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/api_gateway/d_api_gateway_1.tf" }}
        /// </summary>
        public static Task<GetApiGatewayResult> InvokeAsync(GetApiGatewayArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetApiGatewayResult>("yandex:index/getApiGateway:getApiGateway", args ?? new GetApiGatewayArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Cloud API Gateway. For more information, see the official documentation [Yandex Cloud API Gateway](https://cloud.yandex.com/docs/api-gateway/).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/api_gateway/d_api_gateway_1.tf" }}
        /// </summary>
        public static Output<GetApiGatewayResult> Invoke(GetApiGatewayInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetApiGatewayResult>("yandex:index/getApiGateway:getApiGateway", args ?? new GetApiGatewayInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Cloud API Gateway. For more information, see the official documentation [Yandex Cloud API Gateway](https://cloud.yandex.com/docs/api-gateway/).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/api_gateway/d_api_gateway_1.tf" }}
        /// </summary>
        public static Output<GetApiGatewayResult> Invoke(GetApiGatewayInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetApiGatewayResult>("yandex:index/getApiGateway:getApiGateway", args ?? new GetApiGatewayInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetApiGatewayArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Yandex Cloud API Gateway id used to define api gateway.
        /// </summary>
        [Input("apiGatewayId")]
        public string? ApiGatewayId { get; set; }

        /// <summary>
        /// Canary release settings of gateway.
        /// </summary>
        [Input("canary")]
        public Inputs.GetApiGatewayCanaryArgs? Canary { get; set; }

        /// <summary>
        /// Gateway connectivity. If specified the gateway will be attached to specified network.
        /// </summary>
        [Input("connectivity")]
        public Inputs.GetApiGatewayConnectivityArgs? Connectivity { get; set; }

        [Input("customDomains")]
        private List<Inputs.GetApiGatewayCustomDomainArgs>? _customDomains;

        /// <summary>
        /// Set of custom domains attached to Yandex API Gateway. Each set item has the following properties: `domain_id`, `fqdn`, `certificate_id`.
        /// </summary>
        public List<Inputs.GetApiGatewayCustomDomainArgs> CustomDomains
        {
            get => _customDomains ?? (_customDomains = new List<Inputs.GetApiGatewayCustomDomainArgs>());
            set => _customDomains = value;
        }

        /// <summary>
        /// Execution timeout in seconds for the Yandex Cloud API Gateway.
        /// </summary>
        [Input("executionTimeout")]
        public string? ExecutionTimeout { get; set; }

        /// <summary>
        /// Folder ID for the Yandex Cloud API Gateway.
        /// 
        /// &gt; Either `api_gateway_id` or `name` must be specified.
        /// </summary>
        [Input("folderId")]
        public string? FolderId { get; set; }

        /// <summary>
        /// Yandex Cloud API Gateway name used to define api gateway.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        [Input("variables")]
        private Dictionary<string, string>? _variables;

        /// <summary>
        /// A set of values for variables in gateway specification.
        /// </summary>
        public Dictionary<string, string> Variables
        {
            get => _variables ?? (_variables = new Dictionary<string, string>());
            set => _variables = value;
        }

        public GetApiGatewayArgs()
        {
        }
        public static new GetApiGatewayArgs Empty => new GetApiGatewayArgs();
    }

    public sealed class GetApiGatewayInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Yandex Cloud API Gateway id used to define api gateway.
        /// </summary>
        [Input("apiGatewayId")]
        public Input<string>? ApiGatewayId { get; set; }

        /// <summary>
        /// Canary release settings of gateway.
        /// </summary>
        [Input("canary")]
        public Input<Inputs.GetApiGatewayCanaryInputArgs>? Canary { get; set; }

        /// <summary>
        /// Gateway connectivity. If specified the gateway will be attached to specified network.
        /// </summary>
        [Input("connectivity")]
        public Input<Inputs.GetApiGatewayConnectivityInputArgs>? Connectivity { get; set; }

        [Input("customDomains")]
        private InputList<Inputs.GetApiGatewayCustomDomainInputArgs>? _customDomains;

        /// <summary>
        /// Set of custom domains attached to Yandex API Gateway. Each set item has the following properties: `domain_id`, `fqdn`, `certificate_id`.
        /// </summary>
        public InputList<Inputs.GetApiGatewayCustomDomainInputArgs> CustomDomains
        {
            get => _customDomains ?? (_customDomains = new InputList<Inputs.GetApiGatewayCustomDomainInputArgs>());
            set => _customDomains = value;
        }

        /// <summary>
        /// Execution timeout in seconds for the Yandex Cloud API Gateway.
        /// </summary>
        [Input("executionTimeout")]
        public Input<string>? ExecutionTimeout { get; set; }

        /// <summary>
        /// Folder ID for the Yandex Cloud API Gateway.
        /// 
        /// &gt; Either `api_gateway_id` or `name` must be specified.
        /// </summary>
        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        /// <summary>
        /// Yandex Cloud API Gateway name used to define api gateway.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("variables")]
        private InputMap<string>? _variables;

        /// <summary>
        /// A set of values for variables in gateway specification.
        /// </summary>
        public InputMap<string> Variables
        {
            get => _variables ?? (_variables = new InputMap<string>());
            set => _variables = value;
        }

        public GetApiGatewayInvokeArgs()
        {
        }
        public static new GetApiGatewayInvokeArgs Empty => new GetApiGatewayInvokeArgs();
    }


    [OutputType]
    public sealed class GetApiGatewayResult
    {
        public readonly string? ApiGatewayId;
        /// <summary>
        /// Canary release settings of gateway.
        /// </summary>
        public readonly Outputs.GetApiGatewayCanaryResult? Canary;
        /// <summary>
        /// Gateway connectivity. If specified the gateway will be attached to specified network.
        /// </summary>
        public readonly Outputs.GetApiGatewayConnectivityResult? Connectivity;
        /// <summary>
        /// Creation timestamp of the Yandex Cloud API Gateway.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Set of custom domains attached to Yandex API Gateway. Each set item has the following properties: `domain_id`, `fqdn`, `certificate_id`.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetApiGatewayCustomDomainResult> CustomDomains;
        /// <summary>
        /// Description of the Yandex Cloud API Gateway.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Default domain for the Yandex API Gateway.
        /// </summary>
        public readonly string Domain;
        /// <summary>
        /// Execution timeout in seconds for the Yandex Cloud API Gateway.
        /// </summary>
        public readonly string ExecutionTimeout;
        public readonly string? FolderId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A set of key/value label pairs to assign to the Yandex Cloud API Gateway.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Labels;
        public readonly string LogGroupId;
        /// <summary>
        /// Options for logging from Yandex Cloud Function.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetApiGatewayLogOptionResult> LogOptions;
        public readonly string? Name;
        /// <summary>
        /// Status of the Yandex API Gateway.
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// (**DEPRECATED**, use `custom_domains` instead) Set of user domains attached to Yandex API Gateway.
        /// </summary>
        public readonly ImmutableArray<string> UserDomains;
        /// <summary>
        /// A set of values for variables in gateway specification.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Variables;

        [OutputConstructor]
        private GetApiGatewayResult(
            string? apiGatewayId,

            Outputs.GetApiGatewayCanaryResult? canary,

            Outputs.GetApiGatewayConnectivityResult? connectivity,

            string createdAt,

            ImmutableArray<Outputs.GetApiGatewayCustomDomainResult> customDomains,

            string description,

            string domain,

            string executionTimeout,

            string? folderId,

            string id,

            ImmutableDictionary<string, string> labels,

            string logGroupId,

            ImmutableArray<Outputs.GetApiGatewayLogOptionResult> logOptions,

            string? name,

            string status,

            ImmutableArray<string> userDomains,

            ImmutableDictionary<string, string>? variables)
        {
            ApiGatewayId = apiGatewayId;
            Canary = canary;
            Connectivity = connectivity;
            CreatedAt = createdAt;
            CustomDomains = customDomains;
            Description = description;
            Domain = domain;
            ExecutionTimeout = executionTimeout;
            FolderId = folderId;
            Id = id;
            Labels = labels;
            LogGroupId = logGroupId;
            LogOptions = logOptions;
            Name = name;
            Status = status;
            UserDomains = userDomains;
            Variables = variables;
        }
    }
}
