// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetAlbLoadBalancer
    {
        /// <summary>
        /// Get information about a Yandex Application Load Balancer. For more information, see [Yandex Cloud Application Load Balancer](https://yandex.cloud/docs/application-load-balancer/quickstart).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/alb_load_balancer/d_alb_load_balancer_1.tf" }}
        /// 
        /// This data source is used to define [Application Load Balancer](https://yandex.cloud/docs/application-load-balancer/concepts/application-load-balancer) that can be used by other resources.
        /// </summary>
        public static Task<GetAlbLoadBalancerResult> InvokeAsync(GetAlbLoadBalancerArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAlbLoadBalancerResult>("yandex:index/getAlbLoadBalancer:getAlbLoadBalancer", args ?? new GetAlbLoadBalancerArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Application Load Balancer. For more information, see [Yandex Cloud Application Load Balancer](https://yandex.cloud/docs/application-load-balancer/quickstart).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/alb_load_balancer/d_alb_load_balancer_1.tf" }}
        /// 
        /// This data source is used to define [Application Load Balancer](https://yandex.cloud/docs/application-load-balancer/concepts/application-load-balancer) that can be used by other resources.
        /// </summary>
        public static Output<GetAlbLoadBalancerResult> Invoke(GetAlbLoadBalancerInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAlbLoadBalancerResult>("yandex:index/getAlbLoadBalancer:getAlbLoadBalancer", args ?? new GetAlbLoadBalancerInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Application Load Balancer. For more information, see [Yandex Cloud Application Load Balancer](https://yandex.cloud/docs/application-load-balancer/quickstart).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/alb_load_balancer/d_alb_load_balancer_1.tf" }}
        /// 
        /// This data source is used to define [Application Load Balancer](https://yandex.cloud/docs/application-load-balancer/concepts/application-load-balancer) that can be used by other resources.
        /// </summary>
        public static Output<GetAlbLoadBalancerResult> Invoke(GetAlbLoadBalancerInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAlbLoadBalancerResult>("yandex:index/getAlbLoadBalancer:getAlbLoadBalancer", args ?? new GetAlbLoadBalancerInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAlbLoadBalancerArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Load Balancer ID.
        /// </summary>
        [Input("loadBalancerId")]
        public string? LoadBalancerId { get; set; }

        /// <summary>
        /// Name of the Load Balancer.
        /// 
        /// &gt; One of `load_balancer_id` or `name` should be specified.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetAlbLoadBalancerArgs()
        {
        }
        public static new GetAlbLoadBalancerArgs Empty => new GetAlbLoadBalancerArgs();
    }

    public sealed class GetAlbLoadBalancerInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Load Balancer ID.
        /// </summary>
        [Input("loadBalancerId")]
        public Input<string>? LoadBalancerId { get; set; }

        /// <summary>
        /// Name of the Load Balancer.
        /// 
        /// &gt; One of `load_balancer_id` or `name` should be specified.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetAlbLoadBalancerInvokeArgs()
        {
        }
        public static new GetAlbLoadBalancerInvokeArgs Empty => new GetAlbLoadBalancerInvokeArgs();
    }


    [OutputType]
    public sealed class GetAlbLoadBalancerResult
    {
        /// <summary>
        /// Allocation zones for the Load Balancer instance. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAlbLoadBalancerAllocationPolicyResult> AllocationPolicies;
        /// <summary>
        /// The Load Balancer creation timestamp.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// An optional description of the Load Balancer.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The ID of the folder to which the resource belongs. If omitted, the provider folder is used.
        /// </summary>
        public readonly string FolderId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Labels to assign to this Load Balancer. A list of key/value pairs.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Labels;
        /// <summary>
        /// List of listeners for the Load Balancer. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAlbLoadBalancerListenerResult> Listeners;
        public readonly string LoadBalancerId;
        /// <summary>
        /// (Optional) Cloud Logging group ID to send logs to. Leave empty to use the balancer folder default log group.
        /// </summary>
        public readonly string LogGroupId;
        /// <summary>
        /// Cloud Logging settings. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAlbLoadBalancerLogOptionResult> LogOptions;
        /// <summary>
        /// name of SNI match.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// ID of the network that the Load Balancer is located at.
        /// </summary>
        public readonly string NetworkId;
        /// <summary>
        /// ID of the region that the Load Balancer is located at.
        /// </summary>
        public readonly string RegionId;
        /// <summary>
        /// A list of ID's of security groups attached to the Load Balancer.
        /// </summary>
        public readonly ImmutableArray<string> SecurityGroupIds;
        /// <summary>
        /// Status of the Load Balancer.
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private GetAlbLoadBalancerResult(
            ImmutableArray<Outputs.GetAlbLoadBalancerAllocationPolicyResult> allocationPolicies,

            string createdAt,

            string description,

            string folderId,

            string id,

            ImmutableDictionary<string, string> labels,

            ImmutableArray<Outputs.GetAlbLoadBalancerListenerResult> listeners,

            string loadBalancerId,

            string logGroupId,

            ImmutableArray<Outputs.GetAlbLoadBalancerLogOptionResult> logOptions,

            string name,

            string networkId,

            string regionId,

            ImmutableArray<string> securityGroupIds,

            string status)
        {
            AllocationPolicies = allocationPolicies;
            CreatedAt = createdAt;
            Description = description;
            FolderId = folderId;
            Id = id;
            Labels = labels;
            Listeners = listeners;
            LoadBalancerId = loadBalancerId;
            LogGroupId = logGroupId;
            LogOptions = logOptions;
            Name = name;
            NetworkId = networkId;
            RegionId = regionId;
            SecurityGroupIds = securityGroupIds;
            Status = status;
        }
    }
}
