// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetComputeImage
    {
        /// <summary>
        /// Get information about a Yandex Compute image. For more information, see [the official documentation](https://cloud.yandex.com/docs/compute/concepts/image).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/compute_image/d_compute_image_1.tf" }}
        /// </summary>
        public static Task<GetComputeImageResult> InvokeAsync(GetComputeImageArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetComputeImageResult>("yandex:index/getComputeImage:getComputeImage", args ?? new GetComputeImageArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Compute image. For more information, see [the official documentation](https://cloud.yandex.com/docs/compute/concepts/image).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/compute_image/d_compute_image_1.tf" }}
        /// </summary>
        public static Output<GetComputeImageResult> Invoke(GetComputeImageInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetComputeImageResult>("yandex:index/getComputeImage:getComputeImage", args ?? new GetComputeImageInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Compute image. For more information, see [the official documentation](https://cloud.yandex.com/docs/compute/concepts/image).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/compute_image/d_compute_image_1.tf" }}
        /// </summary>
        public static Output<GetComputeImageResult> Invoke(GetComputeImageInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetComputeImageResult>("yandex:index/getComputeImage:getComputeImage", args ?? new GetComputeImageInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetComputeImageArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The family name of an image. Used to search the latest image in a family.
        /// </summary>
        [Input("family")]
        public string? Family { get; set; }

        /// <summary>
        /// Folder that the resource belongs to. If value is omitted, the default provider folder is used.
        /// 
        /// &gt; If you specify `family` without `folder_id` then lookup takes place in the 'standard-images' folder.
        /// </summary>
        [Input("folderId")]
        public string? FolderId { get; set; }

        /// <summary>
        /// The ID of a specific image.
        /// </summary>
        [Input("imageId")]
        public string? ImageId { get; set; }

        /// <summary>
        /// The name of the image.
        /// 
        /// &gt; Either `image_id`, `family` or `name` must be specified.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetComputeImageArgs()
        {
        }
        public static new GetComputeImageArgs Empty => new GetComputeImageArgs();
    }

    public sealed class GetComputeImageInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The family name of an image. Used to search the latest image in a family.
        /// </summary>
        [Input("family")]
        public Input<string>? Family { get; set; }

        /// <summary>
        /// Folder that the resource belongs to. If value is omitted, the default provider folder is used.
        /// 
        /// &gt; If you specify `family` without `folder_id` then lookup takes place in the 'standard-images' folder.
        /// </summary>
        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        /// <summary>
        /// The ID of a specific image.
        /// </summary>
        [Input("imageId")]
        public Input<string>? ImageId { get; set; }

        /// <summary>
        /// The name of the image.
        /// 
        /// &gt; Either `image_id`, `family` or `name` must be specified.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetComputeImageInvokeArgs()
        {
        }
        public static new GetComputeImageInvokeArgs Empty => new GetComputeImageInvokeArgs();
    }


    [OutputType]
    public sealed class GetComputeImageResult
    {
        /// <summary>
        /// Image creation timestamp.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// An optional description of this image.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The OS family name of the image.
        /// </summary>
        public readonly string Family;
        public readonly string FolderId;
        /// <summary>
        /// Image hardware generation and its features. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetComputeImageHardwareGenerationResult> HardwareGenerations;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string ImageId;
        /// <summary>
        /// ID of KMS symmetric key used to encrypt image.
        /// </summary>
        public readonly string KmsKeyId;
        /// <summary>
        /// A map of labels applied to this image.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Labels;
        /// <summary>
        /// Minimum size of the disk which is created from this image.
        /// </summary>
        public readonly int MinDiskSize;
        public readonly string Name;
        /// <summary>
        /// Operating system type that the image contains.
        /// </summary>
        public readonly string OsType;
        /// <summary>
        /// Optimize the image to create a disk.
        /// </summary>
        public readonly bool Pooled;
        /// <summary>
        /// License IDs that indicate which licenses are attached to this image.
        /// </summary>
        public readonly ImmutableArray<string> ProductIds;
        /// <summary>
        /// The size of the image, specified in Gb.
        /// </summary>
        public readonly int Size;
        /// <summary>
        /// The status of the image.
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private GetComputeImageResult(
            string createdAt,

            string description,

            string family,

            string folderId,

            ImmutableArray<Outputs.GetComputeImageHardwareGenerationResult> hardwareGenerations,

            string id,

            string imageId,

            string kmsKeyId,

            ImmutableDictionary<string, string> labels,

            int minDiskSize,

            string name,

            string osType,

            bool pooled,

            ImmutableArray<string> productIds,

            int size,

            string status)
        {
            CreatedAt = createdAt;
            Description = description;
            Family = family;
            FolderId = folderId;
            HardwareGenerations = hardwareGenerations;
            Id = id;
            ImageId = imageId;
            KmsKeyId = kmsKeyId;
            Labels = labels;
            MinDiskSize = minDiskSize;
            Name = name;
            OsType = osType;
            Pooled = pooled;
            ProductIds = productIds;
            Size = size;
            Status = status;
        }
    }
}
