// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetDataprocCluster
    {
        /// <summary>
        /// Get information about a Yandex Data Processing cluster. For more information, see [the official documentation](https://cloud.yandex.com/docs/data-proc/).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/dataproc_cluster/d_dataproc_cluster_1.tf" }}
        /// </summary>
        public static Task<GetDataprocClusterResult> InvokeAsync(GetDataprocClusterArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDataprocClusterResult>("yandex:index/getDataprocCluster:getDataprocCluster", args ?? new GetDataprocClusterArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Data Processing cluster. For more information, see [the official documentation](https://cloud.yandex.com/docs/data-proc/).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/dataproc_cluster/d_dataproc_cluster_1.tf" }}
        /// </summary>
        public static Output<GetDataprocClusterResult> Invoke(GetDataprocClusterInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDataprocClusterResult>("yandex:index/getDataprocCluster:getDataprocCluster", args ?? new GetDataprocClusterInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Data Processing cluster. For more information, see [the official documentation](https://cloud.yandex.com/docs/data-proc/).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/dataproc_cluster/d_dataproc_cluster_1.tf" }}
        /// </summary>
        public static Output<GetDataprocClusterResult> Invoke(GetDataprocClusterInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDataprocClusterResult>("yandex:index/getDataprocCluster:getDataprocCluster", args ?? new GetDataprocClusterInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDataprocClusterArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the Yandex Data Processing cluster.
        /// </summary>
        [Input("clusterId")]
        public string? ClusterId { get; set; }

        /// <summary>
        /// The name of the Yandex Data Processing cluster.
        /// 
        /// &gt; Either `cluster_id` or `name` should be specified.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetDataprocClusterArgs()
        {
        }
        public static new GetDataprocClusterArgs Empty => new GetDataprocClusterArgs();
    }

    public sealed class GetDataprocClusterInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the Yandex Data Processing cluster.
        /// </summary>
        [Input("clusterId")]
        public Input<string>? ClusterId { get; set; }

        /// <summary>
        /// The name of the Yandex Data Processing cluster.
        /// 
        /// &gt; Either `cluster_id` or `name` should be specified.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetDataprocClusterInvokeArgs()
        {
        }
        public static new GetDataprocClusterInvokeArgs Empty => new GetDataprocClusterInvokeArgs();
    }


    [OutputType]
    public sealed class GetDataprocClusterResult
    {
        /// <summary>
        /// Name of the Object Storage bucket used for Yandex Data Processing jobs.
        /// </summary>
        public readonly string Bucket;
        /// <summary>
        /// Configuration and resources of the cluster. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDataprocClusterClusterConfigResult> ClusterConfigs;
        public readonly string ClusterId;
        /// <summary>
        /// The Yandex Data Processing cluster creation timestamp.
        /// </summary>
        public readonly string CreatedAt;
        public readonly bool DeletionProtection;
        /// <summary>
        /// Description of the Yandex Data Processing cluster.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Deployment environment of the cluster. Can be either `PRESTABLE` or `PRODUCTION`.
        /// </summary>
        public readonly string Environment;
        public readonly string FolderId;
        /// <summary>
        /// A list of IDs of the host groups hosting VMs of the cluster.
        /// </summary>
        public readonly ImmutableArray<string> HostGroupIds;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A set of key/value label pairs assigned to the Yandex Data Processing cluster.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Labels;
        /// <summary>
        /// ID of the cloud logging group for cluster logs.
        /// </summary>
        public readonly string LogGroupId;
        /// <summary>
        /// Name of the Yandex Data Processing subcluster.
        /// </summary>
        public readonly string Name;
        public readonly ImmutableArray<string> SecurityGroupIds;
        /// <summary>
        /// Service account used by the Yandex Data Processing agent to access resources of Yandex Cloud.
        /// </summary>
        public readonly string ServiceAccountId;
        /// <summary>
        /// Whether UI proxy feature is enabled.
        /// </summary>
        public readonly bool UiProxy;
        /// <summary>
        /// ID of the availability zone where the cluster resides.
        /// </summary>
        public readonly string ZoneId;

        [OutputConstructor]
        private GetDataprocClusterResult(
            string bucket,

            ImmutableArray<Outputs.GetDataprocClusterClusterConfigResult> clusterConfigs,

            string clusterId,

            string createdAt,

            bool deletionProtection,

            string description,

            string environment,

            string folderId,

            ImmutableArray<string> hostGroupIds,

            string id,

            ImmutableDictionary<string, string> labels,

            string logGroupId,

            string name,

            ImmutableArray<string> securityGroupIds,

            string serviceAccountId,

            bool uiProxy,

            string zoneId)
        {
            Bucket = bucket;
            ClusterConfigs = clusterConfigs;
            ClusterId = clusterId;
            CreatedAt = createdAt;
            DeletionProtection = deletionProtection;
            Description = description;
            Environment = environment;
            FolderId = folderId;
            HostGroupIds = hostGroupIds;
            Id = id;
            Labels = labels;
            LogGroupId = logGroupId;
            Name = name;
            SecurityGroupIds = securityGroupIds;
            ServiceAccountId = serviceAccountId;
            UiProxy = uiProxy;
            ZoneId = zoneId;
        }
    }
}
