// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetFunctionScalingPolicy
    {
        /// <summary>
        /// Get information about a Yandex Cloud Function Scaling Policy. For more information about Yandex Cloud Functions, see [Yandex Cloud Functions](https://cloud.yandex.com/docs/functions/).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/function_scaling_policy/d_function_scaling_policy_1.tf" }}
        /// 
        /// This data source is used to define [Yandex Cloud Function Scaling Policy](https://cloud.yandex.com/docs/functions/) that can be used by other resources.
        /// </summary>
        public static Task<GetFunctionScalingPolicyResult> InvokeAsync(GetFunctionScalingPolicyArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetFunctionScalingPolicyResult>("yandex:index/getFunctionScalingPolicy:getFunctionScalingPolicy", args ?? new GetFunctionScalingPolicyArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Cloud Function Scaling Policy. For more information about Yandex Cloud Functions, see [Yandex Cloud Functions](https://cloud.yandex.com/docs/functions/).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/function_scaling_policy/d_function_scaling_policy_1.tf" }}
        /// 
        /// This data source is used to define [Yandex Cloud Function Scaling Policy](https://cloud.yandex.com/docs/functions/) that can be used by other resources.
        /// </summary>
        public static Output<GetFunctionScalingPolicyResult> Invoke(GetFunctionScalingPolicyInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetFunctionScalingPolicyResult>("yandex:index/getFunctionScalingPolicy:getFunctionScalingPolicy", args ?? new GetFunctionScalingPolicyInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Cloud Function Scaling Policy. For more information about Yandex Cloud Functions, see [Yandex Cloud Functions](https://cloud.yandex.com/docs/functions/).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/function_scaling_policy/d_function_scaling_policy_1.tf" }}
        /// 
        /// This data source is used to define [Yandex Cloud Function Scaling Policy](https://cloud.yandex.com/docs/functions/) that can be used by other resources.
        /// </summary>
        public static Output<GetFunctionScalingPolicyResult> Invoke(GetFunctionScalingPolicyInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetFunctionScalingPolicyResult>("yandex:index/getFunctionScalingPolicy:getFunctionScalingPolicy", args ?? new GetFunctionScalingPolicyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetFunctionScalingPolicyArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Yandex Cloud Function id used to define function
        /// </summary>
        [Input("functionId", required: true)]
        public string FunctionId { get; set; } = null!;

        [Input("policies")]
        private List<Inputs.GetFunctionScalingPolicyPolicyArgs>? _policies;

        /// <summary>
        /// list definition for Yandex Cloud Function scaling policies
        /// * `policy.#` - number of Yandex Cloud Function scaling policies
        /// * `policy.{num}.tag` - Yandex Cloud Function version tag for Yandex Cloud Function scaling policy
        /// * `policy.{num}.zone_instances_limit` - max number of instances in one zone for Yandex Cloud Function with tag
        /// * `policy.{num}.zone_requests_limit` - max number of requests in one zone for Yandex Cloud Function with tag
        /// </summary>
        public List<Inputs.GetFunctionScalingPolicyPolicyArgs> Policies
        {
            get => _policies ?? (_policies = new List<Inputs.GetFunctionScalingPolicyPolicyArgs>());
            set => _policies = value;
        }

        public GetFunctionScalingPolicyArgs()
        {
        }
        public static new GetFunctionScalingPolicyArgs Empty => new GetFunctionScalingPolicyArgs();
    }

    public sealed class GetFunctionScalingPolicyInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Yandex Cloud Function id used to define function
        /// </summary>
        [Input("functionId", required: true)]
        public Input<string> FunctionId { get; set; } = null!;

        [Input("policies")]
        private InputList<Inputs.GetFunctionScalingPolicyPolicyInputArgs>? _policies;

        /// <summary>
        /// list definition for Yandex Cloud Function scaling policies
        /// * `policy.#` - number of Yandex Cloud Function scaling policies
        /// * `policy.{num}.tag` - Yandex Cloud Function version tag for Yandex Cloud Function scaling policy
        /// * `policy.{num}.zone_instances_limit` - max number of instances in one zone for Yandex Cloud Function with tag
        /// * `policy.{num}.zone_requests_limit` - max number of requests in one zone for Yandex Cloud Function with tag
        /// </summary>
        public InputList<Inputs.GetFunctionScalingPolicyPolicyInputArgs> Policies
        {
            get => _policies ?? (_policies = new InputList<Inputs.GetFunctionScalingPolicyPolicyInputArgs>());
            set => _policies = value;
        }

        public GetFunctionScalingPolicyInvokeArgs()
        {
        }
        public static new GetFunctionScalingPolicyInvokeArgs Empty => new GetFunctionScalingPolicyInvokeArgs();
    }


    [OutputType]
    public sealed class GetFunctionScalingPolicyResult
    {
        public readonly string FunctionId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// list definition for Yandex Cloud Function scaling policies
        /// * `policy.#` - number of Yandex Cloud Function scaling policies
        /// * `policy.{num}.tag` - Yandex Cloud Function version tag for Yandex Cloud Function scaling policy
        /// * `policy.{num}.zone_instances_limit` - max number of instances in one zone for Yandex Cloud Function with tag
        /// * `policy.{num}.zone_requests_limit` - max number of requests in one zone for Yandex Cloud Function with tag
        /// </summary>
        public readonly ImmutableArray<Outputs.GetFunctionScalingPolicyPolicyResult> Policies;

        [OutputConstructor]
        private GetFunctionScalingPolicyResult(
            string functionId,

            string id,

            ImmutableArray<Outputs.GetFunctionScalingPolicyPolicyResult> policies)
        {
            FunctionId = functionId;
            Id = id;
            Policies = policies;
        }
    }
}
