// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetLoadtestingAgent
    {
        /// <summary>
        /// Get information about a Yandex Load Testing Agent.
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/loadtesting_agent/d_loadtesting_agent_1.tf" }}
        /// </summary>
        public static Task<GetLoadtestingAgentResult> InvokeAsync(GetLoadtestingAgentArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetLoadtestingAgentResult>("yandex:index/getLoadtestingAgent:getLoadtestingAgent", args ?? new GetLoadtestingAgentArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Load Testing Agent.
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/loadtesting_agent/d_loadtesting_agent_1.tf" }}
        /// </summary>
        public static Output<GetLoadtestingAgentResult> Invoke(GetLoadtestingAgentInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetLoadtestingAgentResult>("yandex:index/getLoadtestingAgent:getLoadtestingAgent", args ?? new GetLoadtestingAgentInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex Load Testing Agent.
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/loadtesting_agent/d_loadtesting_agent_1.tf" }}
        /// </summary>
        public static Output<GetLoadtestingAgentResult> Invoke(GetLoadtestingAgentInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetLoadtestingAgentResult>("yandex:index/getLoadtestingAgent:getLoadtestingAgent", args ?? new GetLoadtestingAgentInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetLoadtestingAgentArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of a specific load testing agent.
        /// </summary>
        [Input("agentId", required: true)]
        public string AgentId { get; set; } = null!;

        /// <summary>
        /// The logging settings of the load testing agent. The structure is documented below.
        /// </summary>
        [Input("logSettings")]
        public Inputs.GetLoadtestingAgentLogSettingsArgs? LogSettings { get; set; }

        public GetLoadtestingAgentArgs()
        {
        }
        public static new GetLoadtestingAgentArgs Empty => new GetLoadtestingAgentArgs();
    }

    public sealed class GetLoadtestingAgentInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of a specific load testing agent.
        /// </summary>
        [Input("agentId", required: true)]
        public Input<string> AgentId { get; set; } = null!;

        /// <summary>
        /// The logging settings of the load testing agent. The structure is documented below.
        /// </summary>
        [Input("logSettings")]
        public Input<Inputs.GetLoadtestingAgentLogSettingsInputArgs>? LogSettings { get; set; }

        public GetLoadtestingAgentInvokeArgs()
        {
        }
        public static new GetLoadtestingAgentInvokeArgs Empty => new GetLoadtestingAgentInvokeArgs();
    }


    [OutputType]
    public sealed class GetLoadtestingAgentResult
    {
        public readonly string AgentId;
        /// <summary>
        /// The ID of Yandex Compute Instance running loadtesting agent.
        /// </summary>
        public readonly string ComputeInstanceId;
        /// <summary>
        /// The Compute Instance details. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetLoadtestingAgentComputeInstanceResult> ComputeInstances;
        /// <summary>
        /// A description of the boot disk.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The ID of the folder that the load testing agent belongs to.
        /// </summary>
        public readonly string FolderId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A map of labels applied to the load testing agent.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Labels;
        /// <summary>
        /// The logging settings of the load testing agent. The structure is documented below.
        /// </summary>
        public readonly Outputs.GetLoadtestingAgentLogSettingsResult? LogSettings;
        /// <summary>
        /// The name of the boot disk.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetLoadtestingAgentResult(
            string agentId,

            string computeInstanceId,

            ImmutableArray<Outputs.GetLoadtestingAgentComputeInstanceResult> computeInstances,

            string description,

            string folderId,

            string id,

            ImmutableDictionary<string, string> labels,

            Outputs.GetLoadtestingAgentLogSettingsResult? logSettings,

            string name)
        {
            AgentId = agentId;
            ComputeInstanceId = computeInstanceId;
            ComputeInstances = computeInstances;
            Description = description;
            FolderId = folderId;
            Id = id;
            Labels = labels;
            LogSettings = logSettings;
            Name = name;
        }
    }
}
