// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetSmartcaptchaCaptcha
    {
        /// <summary>
        /// Get information about Yandex SmartCaptcha. For more information, see [the official documentation](https://yandex.cloud/docs/smartcaptcha/).
        /// 
        /// This data source is used to define Captcha that can be used by other resources.
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/smartcaptcha_captcha/d_smartcaptcha_captcha_1.tf" }}
        /// 
        /// {{ tffile "examples/smartcaptcha_captcha/d_smartcaptcha_captcha_2.tf" }}
        /// </summary>
        public static Task<GetSmartcaptchaCaptchaResult> InvokeAsync(GetSmartcaptchaCaptchaArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSmartcaptchaCaptchaResult>("yandex:index/getSmartcaptchaCaptcha:getSmartcaptchaCaptcha", args ?? new GetSmartcaptchaCaptchaArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about Yandex SmartCaptcha. For more information, see [the official documentation](https://yandex.cloud/docs/smartcaptcha/).
        /// 
        /// This data source is used to define Captcha that can be used by other resources.
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/smartcaptcha_captcha/d_smartcaptcha_captcha_1.tf" }}
        /// 
        /// {{ tffile "examples/smartcaptcha_captcha/d_smartcaptcha_captcha_2.tf" }}
        /// </summary>
        public static Output<GetSmartcaptchaCaptchaResult> Invoke(GetSmartcaptchaCaptchaInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSmartcaptchaCaptchaResult>("yandex:index/getSmartcaptchaCaptcha:getSmartcaptchaCaptcha", args ?? new GetSmartcaptchaCaptchaInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about Yandex SmartCaptcha. For more information, see [the official documentation](https://yandex.cloud/docs/smartcaptcha/).
        /// 
        /// This data source is used to define Captcha that can be used by other resources.
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/smartcaptcha_captcha/d_smartcaptcha_captcha_1.tf" }}
        /// 
        /// {{ tffile "examples/smartcaptcha_captcha/d_smartcaptcha_captcha_2.tf" }}
        /// </summary>
        public static Output<GetSmartcaptchaCaptchaResult> Invoke(GetSmartcaptchaCaptchaInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSmartcaptchaCaptchaResult>("yandex:index/getSmartcaptchaCaptcha:getSmartcaptchaCaptcha", args ?? new GetSmartcaptchaCaptchaInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSmartcaptchaCaptchaArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of the Captcha.
        /// 
        /// &gt; One of `captcha_id` or `name` should be specified.
        /// </summary>
        [Input("captchaId")]
        public string? CaptchaId { get; set; }

        [Input("cloudId")]
        public string? CloudId { get; set; }

        [Input("folderId")]
        public string? FolderId { get; set; }

        /// <summary>
        /// Name of the Captcha.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetSmartcaptchaCaptchaArgs()
        {
        }
        public static new GetSmartcaptchaCaptchaArgs Empty => new GetSmartcaptchaCaptchaArgs();
    }

    public sealed class GetSmartcaptchaCaptchaInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of the Captcha.
        /// 
        /// &gt; One of `captcha_id` or `name` should be specified.
        /// </summary>
        [Input("captchaId")]
        public Input<string>? CaptchaId { get; set; }

        [Input("cloudId")]
        public Input<string>? CloudId { get; set; }

        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        /// <summary>
        /// Name of the Captcha.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetSmartcaptchaCaptchaInvokeArgs()
        {
        }
        public static new GetSmartcaptchaCaptchaInvokeArgs Empty => new GetSmartcaptchaCaptchaInvokeArgs();
    }


    [OutputType]
    public sealed class GetSmartcaptchaCaptchaResult
    {
        /// <summary>
        /// List of allowed host names, see [Domain validation](https://yandex.cloud/docs/smartcaptcha/concepts/domain-validation).
        /// </summary>
        public readonly ImmutableArray<string> AllowedSites;
        public readonly string? CaptchaId;
        /// <summary>
        /// Additional task type of the captcha. Possible values are documented below.
        /// </summary>
        public readonly string ChallengeType;
        /// <summary>
        /// Client key of the captcha, see [CAPTCHA keys](https://yandex.cloud/docs/smartcaptcha/concepts/keys).
        /// </summary>
        public readonly string ClientKey;
        public readonly string CloudId;
        /// <summary>
        /// Complexity of the captcha.
        /// </summary>
        public readonly string Complexity;
        /// <summary>
        /// The Captcha creation timestamp.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Determines whether captcha is protected from being deleted.
        /// </summary>
        public readonly bool DeletionProtection;
        public readonly string FolderId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Name of the rule. The name is unique within the captcha. 1-50 characters long.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// List of variants to use in security_rules. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSmartcaptchaCaptchaOverrideVariantResult> OverrideVariants;
        /// <summary>
        /// Additional task type of the captcha.
        /// </summary>
        public readonly string PreCheckType;
        /// <summary>
        /// List of security rules. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSmartcaptchaCaptchaSecurityRuleResult> SecurityRules;
        /// <summary>
        /// JSON with variables to define the captcha appearance. For more details see generated JSON in cloud console.
        /// </summary>
        public readonly string StyleJson;
        public readonly bool Suspend;
        /// <summary>
        /// Turn off host name check, see [Domain validation](https://yandex.cloud/docs/smartcaptcha/concepts/domain-validation).
        /// </summary>
        public readonly bool TurnOffHostnameCheck;

        [OutputConstructor]
        private GetSmartcaptchaCaptchaResult(
            ImmutableArray<string> allowedSites,

            string? captchaId,

            string challengeType,

            string clientKey,

            string cloudId,

            string complexity,

            string createdAt,

            bool deletionProtection,

            string folderId,

            string id,

            string name,

            ImmutableArray<Outputs.GetSmartcaptchaCaptchaOverrideVariantResult> overrideVariants,

            string preCheckType,

            ImmutableArray<Outputs.GetSmartcaptchaCaptchaSecurityRuleResult> securityRules,

            string styleJson,

            bool suspend,

            bool turnOffHostnameCheck)
        {
            AllowedSites = allowedSites;
            CaptchaId = captchaId;
            ChallengeType = challengeType;
            ClientKey = clientKey;
            CloudId = cloudId;
            Complexity = complexity;
            CreatedAt = createdAt;
            DeletionProtection = deletionProtection;
            FolderId = folderId;
            Id = id;
            Name = name;
            OverrideVariants = overrideVariants;
            PreCheckType = preCheckType;
            SecurityRules = securityRules;
            StyleJson = styleJson;
            Suspend = suspend;
            TurnOffHostnameCheck = turnOffHostnameCheck;
        }
    }
}
