// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetSwsWafProfile
    {
        /// <summary>
        /// Get information about WAF Profile. For more information, see [the official documentation](https://yandex.cloud/docs/smartwebsecurity/quickstart#waf).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/sws_waf_profile/d_sws_waf_profile_1.tf" }}
        /// 
        /// {{ tffile "examples/sws_waf_profile/d_sws_waf_profile_2.tf" }}
        /// 
        /// This data source is used to define WAF Profile that can be used by other resources.
        /// </summary>
        public static Task<GetSwsWafProfileResult> InvokeAsync(GetSwsWafProfileArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSwsWafProfileResult>("yandex:index/getSwsWafProfile:getSwsWafProfile", args ?? new GetSwsWafProfileArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about WAF Profile. For more information, see [the official documentation](https://yandex.cloud/docs/smartwebsecurity/quickstart#waf).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/sws_waf_profile/d_sws_waf_profile_1.tf" }}
        /// 
        /// {{ tffile "examples/sws_waf_profile/d_sws_waf_profile_2.tf" }}
        /// 
        /// This data source is used to define WAF Profile that can be used by other resources.
        /// </summary>
        public static Output<GetSwsWafProfileResult> Invoke(GetSwsWafProfileInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSwsWafProfileResult>("yandex:index/getSwsWafProfile:getSwsWafProfile", args ?? new GetSwsWafProfileInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about WAF Profile. For more information, see [the official documentation](https://yandex.cloud/docs/smartwebsecurity/quickstart#waf).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/sws_waf_profile/d_sws_waf_profile_1.tf" }}
        /// 
        /// {{ tffile "examples/sws_waf_profile/d_sws_waf_profile_2.tf" }}
        /// 
        /// This data source is used to define WAF Profile that can be used by other resources.
        /// </summary>
        public static Output<GetSwsWafProfileResult> Invoke(GetSwsWafProfileInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSwsWafProfileResult>("yandex:index/getSwsWafProfile:getSwsWafProfile", args ?? new GetSwsWafProfileInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSwsWafProfileArgs : global::Pulumi.InvokeArgs
    {
        [Input("cloudId")]
        public string? CloudId { get; set; }

        /// <summary>
        /// ID of the folder to create a profile in. If omitted, the provider folder is used.
        /// </summary>
        [Input("folderId")]
        public string? FolderId { get; set; }

        /// <summary>
        /// Name of the WAF profile.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// ID of the WAF profile.
        /// 
        /// &gt; One of `waf_profile_id` or `name` should be specified.
        /// </summary>
        [Input("wafProfileId")]
        public string? WafProfileId { get; set; }

        public GetSwsWafProfileArgs()
        {
        }
        public static new GetSwsWafProfileArgs Empty => new GetSwsWafProfileArgs();
    }

    public sealed class GetSwsWafProfileInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("cloudId")]
        public Input<string>? CloudId { get; set; }

        /// <summary>
        /// ID of the folder to create a profile in. If omitted, the provider folder is used.
        /// </summary>
        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        /// <summary>
        /// Name of the WAF profile.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// ID of the WAF profile.
        /// 
        /// &gt; One of `waf_profile_id` or `name` should be specified.
        /// </summary>
        [Input("wafProfileId")]
        public Input<string>? WafProfileId { get; set; }

        public GetSwsWafProfileInvokeArgs()
        {
        }
        public static new GetSwsWafProfileInvokeArgs Empty => new GetSwsWafProfileInvokeArgs();
    }


    [OutputType]
    public sealed class GetSwsWafProfileResult
    {
        /// <summary>
        /// Parameters for request body analyzer. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSwsWafProfileAnalyzeRequestBodyResult> AnalyzeRequestBodies;
        public readonly string CloudId;
        /// <summary>
        /// Core rule set settings. See [Basic rule set](https://yandex.cloud/en/docs/smartwebsecurity/concepts/waf#rules-set) for details. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSwsWafProfileCoreRuleSetResult> CoreRuleSets;
        /// <summary>
        /// The profile creation timestamp.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Optional description of the rule. 0-512 characters long.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// List of exclusion rules. See [Rules](https://yandex.cloud/en/docs/smartwebsecurity/concepts/waf#exclusion-rules). The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSwsWafProfileExclusionRuleResult> ExclusionRules;
        /// <summary>
        /// ID of the folder to create a profile in. If omitted, the provider folder is used.
        /// </summary>
        public readonly string FolderId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Labels as key:value pairs. Maximum of 64 per resource.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Labels;
        /// <summary>
        /// Name of exclusion rule.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Settings for each rule in rule set. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSwsWafProfileRuleResult> Rules;
        public readonly string? WafProfileId;

        [OutputConstructor]
        private GetSwsWafProfileResult(
            ImmutableArray<Outputs.GetSwsWafProfileAnalyzeRequestBodyResult> analyzeRequestBodies,

            string cloudId,

            ImmutableArray<Outputs.GetSwsWafProfileCoreRuleSetResult> coreRuleSets,

            string createdAt,

            string description,

            ImmutableArray<Outputs.GetSwsWafProfileExclusionRuleResult> exclusionRules,

            string folderId,

            string id,

            ImmutableDictionary<string, string> labels,

            string name,

            ImmutableArray<Outputs.GetSwsWafProfileRuleResult> rules,

            string? wafProfileId)
        {
            AnalyzeRequestBodies = analyzeRequestBodies;
            CloudId = cloudId;
            CoreRuleSets = coreRuleSets;
            CreatedAt = createdAt;
            Description = description;
            ExclusionRules = exclusionRules;
            FolderId = folderId;
            Id = id;
            Labels = labels;
            Name = name;
            Rules = rules;
            WafProfileId = wafProfileId;
        }
    }
}
