// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetSwsSecurityProfile
    {
        /// <summary>
        /// Get information about SecurityProfile. For more information, see [the official documentation](https://yandex.cloud/docs/smartwebsecurity/concepts/profiles).
        /// 
        /// This data source is used to define SecurityProfile that can be used by other resources.
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/sws_security_profile/d_sws_security_profile_1.tf" }}
        /// 
        /// {{ tffile "examples/sws_security_profile/d_sws_security_profile_2.tf" }}
        /// </summary>
        public static Task<GetSwsSecurityProfileResult> InvokeAsync(GetSwsSecurityProfileArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSwsSecurityProfileResult>("yandex:index/getSwsSecurityProfile:getSwsSecurityProfile", args ?? new GetSwsSecurityProfileArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about SecurityProfile. For more information, see [the official documentation](https://yandex.cloud/docs/smartwebsecurity/concepts/profiles).
        /// 
        /// This data source is used to define SecurityProfile that can be used by other resources.
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/sws_security_profile/d_sws_security_profile_1.tf" }}
        /// 
        /// {{ tffile "examples/sws_security_profile/d_sws_security_profile_2.tf" }}
        /// </summary>
        public static Output<GetSwsSecurityProfileResult> Invoke(GetSwsSecurityProfileInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSwsSecurityProfileResult>("yandex:index/getSwsSecurityProfile:getSwsSecurityProfile", args ?? new GetSwsSecurityProfileInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about SecurityProfile. For more information, see [the official documentation](https://yandex.cloud/docs/smartwebsecurity/concepts/profiles).
        /// 
        /// This data source is used to define SecurityProfile that can be used by other resources.
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/sws_security_profile/d_sws_security_profile_1.tf" }}
        /// 
        /// {{ tffile "examples/sws_security_profile/d_sws_security_profile_2.tf" }}
        /// </summary>
        public static Output<GetSwsSecurityProfileResult> Invoke(GetSwsSecurityProfileInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSwsSecurityProfileResult>("yandex:index/getSwsSecurityProfile:getSwsSecurityProfile", args ?? new GetSwsSecurityProfileInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSwsSecurityProfileArgs : global::Pulumi.InvokeArgs
    {
        [Input("cloudId")]
        public string? CloudId { get; set; }

        [Input("folderId")]
        public string? FolderId { get; set; }

        /// <summary>
        /// Name of the security profile.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// ID of the security profile.
        /// 
        /// &gt; One of `security_profile_id` or `name` should be specified.
        /// </summary>
        [Input("securityProfileId")]
        public string? SecurityProfileId { get; set; }

        public GetSwsSecurityProfileArgs()
        {
        }
        public static new GetSwsSecurityProfileArgs Empty => new GetSwsSecurityProfileArgs();
    }

    public sealed class GetSwsSecurityProfileInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("cloudId")]
        public Input<string>? CloudId { get; set; }

        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        /// <summary>
        /// Name of the security profile.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// ID of the security profile.
        /// 
        /// &gt; One of `security_profile_id` or `name` should be specified.
        /// </summary>
        [Input("securityProfileId")]
        public Input<string>? SecurityProfileId { get; set; }

        public GetSwsSecurityProfileInvokeArgs()
        {
        }
        public static new GetSwsSecurityProfileInvokeArgs Empty => new GetSwsSecurityProfileInvokeArgs();
    }


    [OutputType]
    public sealed class GetSwsSecurityProfileResult
    {
        /// <summary>
        /// Advanced rate limiter profile ID to use with this security profile. Set empty to use default.
        /// </summary>
        public readonly string AdvancedRateLimiterProfileId;
        /// <summary>
        /// Captcha ID to use with this security profile. Set empty to use default.
        /// </summary>
        public readonly string CaptchaId;
        public readonly string CloudId;
        /// <summary>
        /// The profile creation timestamp.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Action to perform if none of rules matched. Possible values: `ALLOW` or `DENY`.
        /// </summary>
        public readonly string DefaultAction;
        /// <summary>
        /// Optional description of the rule. 0-512 characters long.
        /// </summary>
        public readonly string Description;
        public readonly string FolderId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Labels as key:value pairs. Maximum of 64 per resource.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Labels;
        /// <summary>
        /// Name of the rule. The name is unique within the security profile. 1-50 characters long.
        /// </summary>
        public readonly string Name;
        public readonly string? SecurityProfileId;
        /// <summary>
        /// List of security rules. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleResult> SecurityRules;

        [OutputConstructor]
        private GetSwsSecurityProfileResult(
            string advancedRateLimiterProfileId,

            string captchaId,

            string cloudId,

            string createdAt,

            string defaultAction,

            string description,

            string folderId,

            string id,

            ImmutableDictionary<string, string> labels,

            string name,

            string? securityProfileId,

            ImmutableArray<Outputs.GetSwsSecurityProfileSecurityRuleResult> securityRules)
        {
            AdvancedRateLimiterProfileId = advancedRateLimiterProfileId;
            CaptchaId = captchaId;
            CloudId = cloudId;
            CreatedAt = createdAt;
            DefaultAction = defaultAction;
            Description = description;
            FolderId = folderId;
            Id = id;
            Labels = labels;
            Name = name;
            SecurityProfileId = securityProfileId;
            SecurityRules = securityRules;
        }
    }
}
