// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetVpcPrivateEndpoint
    {
        /// <summary>
        /// Get information about a Yandex VPC Private Endpoint. For more information, see [Yandex Cloud VPC](https://cloud.yandex.com/docs/vpc/concepts/index).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/vpc_private_endpoint/d_vpc_private_endpoint_1.tf" }}
        /// 
        /// This data source is used to define [VPC Private Endpoint](https://cloud.yandex.com/docs/vpc/concepts/private-endpoint) that can be used by other resources.
        /// </summary>
        public static Task<GetVpcPrivateEndpointResult> InvokeAsync(GetVpcPrivateEndpointArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetVpcPrivateEndpointResult>("yandex:index/getVpcPrivateEndpoint:getVpcPrivateEndpoint", args ?? new GetVpcPrivateEndpointArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex VPC Private Endpoint. For more information, see [Yandex Cloud VPC](https://cloud.yandex.com/docs/vpc/concepts/index).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/vpc_private_endpoint/d_vpc_private_endpoint_1.tf" }}
        /// 
        /// This data source is used to define [VPC Private Endpoint](https://cloud.yandex.com/docs/vpc/concepts/private-endpoint) that can be used by other resources.
        /// </summary>
        public static Output<GetVpcPrivateEndpointResult> Invoke(GetVpcPrivateEndpointInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetVpcPrivateEndpointResult>("yandex:index/getVpcPrivateEndpoint:getVpcPrivateEndpoint", args ?? new GetVpcPrivateEndpointInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about a Yandex VPC Private Endpoint. For more information, see [Yandex Cloud VPC](https://cloud.yandex.com/docs/vpc/concepts/index).
        /// 
        /// ## Example Usage
        /// 
        /// {{ tffile "examples/vpc_private_endpoint/d_vpc_private_endpoint_1.tf" }}
        /// 
        /// This data source is used to define [VPC Private Endpoint](https://cloud.yandex.com/docs/vpc/concepts/private-endpoint) that can be used by other resources.
        /// </summary>
        public static Output<GetVpcPrivateEndpointResult> Invoke(GetVpcPrivateEndpointInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetVpcPrivateEndpointResult>("yandex:index/getVpcPrivateEndpoint:getVpcPrivateEndpoint", args ?? new GetVpcPrivateEndpointInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetVpcPrivateEndpointArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the private endpoint.
        /// 
        /// &gt; One of `private_endpoint_id` or `name` should be specified.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        [Input("objectStorages")]
        private List<Inputs.GetVpcPrivateEndpointObjectStorageArgs>? _objectStorages;
        public List<Inputs.GetVpcPrivateEndpointObjectStorageArgs> ObjectStorages
        {
            get => _objectStorages ?? (_objectStorages = new List<Inputs.GetVpcPrivateEndpointObjectStorageArgs>());
            set => _objectStorages = value;
        }

        /// <summary>
        /// ID of the private endpoint.
        /// </summary>
        [Input("privateEndpointId")]
        public string? PrivateEndpointId { get; set; }

        public GetVpcPrivateEndpointArgs()
        {
        }
        public static new GetVpcPrivateEndpointArgs Empty => new GetVpcPrivateEndpointArgs();
    }

    public sealed class GetVpcPrivateEndpointInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the private endpoint.
        /// 
        /// &gt; One of `private_endpoint_id` or `name` should be specified.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("objectStorages")]
        private InputList<Inputs.GetVpcPrivateEndpointObjectStorageInputArgs>? _objectStorages;
        public InputList<Inputs.GetVpcPrivateEndpointObjectStorageInputArgs> ObjectStorages
        {
            get => _objectStorages ?? (_objectStorages = new InputList<Inputs.GetVpcPrivateEndpointObjectStorageInputArgs>());
            set => _objectStorages = value;
        }

        /// <summary>
        /// ID of the private endpoint.
        /// </summary>
        [Input("privateEndpointId")]
        public Input<string>? PrivateEndpointId { get; set; }

        public GetVpcPrivateEndpointInvokeArgs()
        {
        }
        public static new GetVpcPrivateEndpointInvokeArgs Empty => new GetVpcPrivateEndpointInvokeArgs();
    }


    [OutputType]
    public sealed class GetVpcPrivateEndpointResult
    {
        /// <summary>
        /// Creation timestamp of this private endpoint.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Description of the private endpoint.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// DNS options of private endpoint.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetVpcPrivateEndpointDnsOptionResult> DnsOptions;
        /// <summary>
        /// Address information of private endpoint.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetVpcPrivateEndpointEndpointAddressResult> EndpointAddresses;
        public readonly string FolderId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Labels assigned to this private endpoint.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Labels;
        public readonly string Name;
        /// <summary>
        /// ID of the network which private endpoint belongs to.
        /// </summary>
        public readonly string NetworkId;
        public readonly ImmutableArray<Outputs.GetVpcPrivateEndpointObjectStorageResult> ObjectStorages;
        public readonly string PrivateEndpointId;
        public readonly string Status;

        [OutputConstructor]
        private GetVpcPrivateEndpointResult(
            string createdAt,

            string description,

            ImmutableArray<Outputs.GetVpcPrivateEndpointDnsOptionResult> dnsOptions,

            ImmutableArray<Outputs.GetVpcPrivateEndpointEndpointAddressResult> endpointAddresses,

            string folderId,

            string id,

            ImmutableDictionary<string, string> labels,

            string name,

            string networkId,

            ImmutableArray<Outputs.GetVpcPrivateEndpointObjectStorageResult> objectStorages,

            string privateEndpointId,

            string status)
        {
            CreatedAt = createdAt;
            Description = description;
            DnsOptions = dnsOptions;
            EndpointAddresses = endpointAddresses;
            FolderId = folderId;
            Id = id;
            Labels = labels;
            Name = name;
            NetworkId = networkId;
            ObjectStorages = objectStorages;
            PrivateEndpointId = privateEndpointId;
            Status = status;
        }
    }
}
