// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    /// <summary>
    /// Allows creation and management of a single member for a single binding within the IAM policy for an existing Yandex KMS Asymmetric Encryption Key.
    /// 
    /// &gt; Roles controlled by `yandex.KmsAsymmetricEncryptionKeyIamBinding` should not be assigned using `yandex.KmsAsymmetricEncryptionKeyIamMember`.
    /// 
    /// ## Example Usage
    /// 
    /// {{ tffile "examples/kms_asymmetric_encryption_key_iam_member/r_kms_asymmetric_encryption_key_iam_member_1.tf" }}
    /// 
    /// ## Import
    /// 
    /// IAM member imports use space-delimited identifiers; the resource in question, the role, and the account. This member resource can be imported using the `asymmetric_encryption_key_id`, role, and account, e.g.
    /// 
    /// ```sh
    /// $ pulumi import yandex:index/kmsAsymmetricEncryptionKeyIamMember:KmsAsymmetricEncryptionKeyIamMember viewer "asymmetric_encryption_key_id viewer foo@example.com"
    /// ```
    /// </summary>
    [YandexResourceType("yandex:index/kmsAsymmetricEncryptionKeyIamMember:KmsAsymmetricEncryptionKeyIamMember")]
    public partial class KmsAsymmetricEncryptionKeyIamMember : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The [Yandex Key Management Service](https://cloud.yandex.com/docs/kms/) Asymmetric Encryption Key ID to apply a binding to.
        /// </summary>
        [Output("asymmetricEncryptionKeyId")]
        public Output<string> AsymmetricEncryptionKeyId { get; private set; } = null!;

        /// <summary>
        /// The identity that will be granted the privilege that is specified in the `role` field. This field can have one of the following values:
        /// * **userAccount:{user_id}**: A unique user ID that represents a specific Yandex account.
        /// * **serviceAccount:{service_account_id}**: A unique service account ID.
        /// * **system:group:federation:{federation_id}:users**: All users in federation.
        /// * **system:group:organization:{organization_id}:users**: All users in organization.
        /// * **system:allAuthenticatedUsers**: All authenticated users.
        /// * **system:allUsers**: All users, including unauthenticated ones.
        /// 
        /// Note: for more information about system groups, see the [documentation](https://cloud.yandex.com/docs/iam/concepts/access-control/system-group).
        /// </summary>
        [Output("member")]
        public Output<string> Member { get; private set; } = null!;

        /// <summary>
        /// The role that should be applied. See [roles](https://cloud.yandex.com/docs/kms/security/).
        /// </summary>
        [Output("role")]
        public Output<string> Role { get; private set; } = null!;

        [Output("sleepAfter")]
        public Output<int?> SleepAfter { get; private set; } = null!;


        /// <summary>
        /// Create a KmsAsymmetricEncryptionKeyIamMember resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public KmsAsymmetricEncryptionKeyIamMember(string name, KmsAsymmetricEncryptionKeyIamMemberArgs args, CustomResourceOptions? options = null)
            : base("yandex:index/kmsAsymmetricEncryptionKeyIamMember:KmsAsymmetricEncryptionKeyIamMember", name, args ?? new KmsAsymmetricEncryptionKeyIamMemberArgs(), MakeResourceOptions(options, ""))
        {
        }

        private KmsAsymmetricEncryptionKeyIamMember(string name, Input<string> id, KmsAsymmetricEncryptionKeyIamMemberState? state = null, CustomResourceOptions? options = null)
            : base("yandex:index/kmsAsymmetricEncryptionKeyIamMember:KmsAsymmetricEncryptionKeyIamMember", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/agorobets/pulumi-yandex/releases",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing KmsAsymmetricEncryptionKeyIamMember resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static KmsAsymmetricEncryptionKeyIamMember Get(string name, Input<string> id, KmsAsymmetricEncryptionKeyIamMemberState? state = null, CustomResourceOptions? options = null)
        {
            return new KmsAsymmetricEncryptionKeyIamMember(name, id, state, options);
        }
    }

    public sealed class KmsAsymmetricEncryptionKeyIamMemberArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The [Yandex Key Management Service](https://cloud.yandex.com/docs/kms/) Asymmetric Encryption Key ID to apply a binding to.
        /// </summary>
        [Input("asymmetricEncryptionKeyId", required: true)]
        public Input<string> AsymmetricEncryptionKeyId { get; set; } = null!;

        /// <summary>
        /// The identity that will be granted the privilege that is specified in the `role` field. This field can have one of the following values:
        /// * **userAccount:{user_id}**: A unique user ID that represents a specific Yandex account.
        /// * **serviceAccount:{service_account_id}**: A unique service account ID.
        /// * **system:group:federation:{federation_id}:users**: All users in federation.
        /// * **system:group:organization:{organization_id}:users**: All users in organization.
        /// * **system:allAuthenticatedUsers**: All authenticated users.
        /// * **system:allUsers**: All users, including unauthenticated ones.
        /// 
        /// Note: for more information about system groups, see the [documentation](https://cloud.yandex.com/docs/iam/concepts/access-control/system-group).
        /// </summary>
        [Input("member", required: true)]
        public Input<string> Member { get; set; } = null!;

        /// <summary>
        /// The role that should be applied. See [roles](https://cloud.yandex.com/docs/kms/security/).
        /// </summary>
        [Input("role", required: true)]
        public Input<string> Role { get; set; } = null!;

        [Input("sleepAfter")]
        public Input<int>? SleepAfter { get; set; }

        public KmsAsymmetricEncryptionKeyIamMemberArgs()
        {
        }
        public static new KmsAsymmetricEncryptionKeyIamMemberArgs Empty => new KmsAsymmetricEncryptionKeyIamMemberArgs();
    }

    public sealed class KmsAsymmetricEncryptionKeyIamMemberState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The [Yandex Key Management Service](https://cloud.yandex.com/docs/kms/) Asymmetric Encryption Key ID to apply a binding to.
        /// </summary>
        [Input("asymmetricEncryptionKeyId")]
        public Input<string>? AsymmetricEncryptionKeyId { get; set; }

        /// <summary>
        /// The identity that will be granted the privilege that is specified in the `role` field. This field can have one of the following values:
        /// * **userAccount:{user_id}**: A unique user ID that represents a specific Yandex account.
        /// * **serviceAccount:{service_account_id}**: A unique service account ID.
        /// * **system:group:federation:{federation_id}:users**: All users in federation.
        /// * **system:group:organization:{organization_id}:users**: All users in organization.
        /// * **system:allAuthenticatedUsers**: All authenticated users.
        /// * **system:allUsers**: All users, including unauthenticated ones.
        /// 
        /// Note: for more information about system groups, see the [documentation](https://cloud.yandex.com/docs/iam/concepts/access-control/system-group).
        /// </summary>
        [Input("member")]
        public Input<string>? Member { get; set; }

        /// <summary>
        /// The role that should be applied. See [roles](https://cloud.yandex.com/docs/kms/security/).
        /// </summary>
        [Input("role")]
        public Input<string>? Role { get; set; }

        [Input("sleepAfter")]
        public Input<int>? SleepAfter { get; set; }

        public KmsAsymmetricEncryptionKeyIamMemberState()
        {
        }
        public static new KmsAsymmetricEncryptionKeyIamMemberState Empty => new KmsAsymmetricEncryptionKeyIamMemberState();
    }
}
