// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/agorobets/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Cloud API Gateway. For more information, see the official documentation [Yandex Cloud API Gateway](https://cloud.yandex.com/docs/api-gateway/).
//
// ## Example Usage
//
// {{ tffile "examples/api_gateway/d_api_gateway_1.tf" }}
func LookupApiGateway(ctx *pulumi.Context, args *LookupApiGatewayArgs, opts ...pulumi.InvokeOption) (*LookupApiGatewayResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupApiGatewayResult
	err := ctx.Invoke("yandex:index/getApiGateway:getApiGateway", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApiGateway.
type LookupApiGatewayArgs struct {
	// Yandex Cloud API Gateway id used to define api gateway.
	ApiGatewayId *string `pulumi:"apiGatewayId"`
	// Canary release settings of gateway.
	Canary *GetApiGatewayCanary `pulumi:"canary"`
	// Gateway connectivity. If specified the gateway will be attached to specified network.
	Connectivity *GetApiGatewayConnectivity `pulumi:"connectivity"`
	// Set of custom domains attached to Yandex API Gateway. Each set item has the following properties: `domainId`, `fqdn`, `certificateId`.
	CustomDomains []GetApiGatewayCustomDomain `pulumi:"customDomains"`
	// Execution timeout in seconds for the Yandex Cloud API Gateway.
	ExecutionTimeout *string `pulumi:"executionTimeout"`
	// Folder ID for the Yandex Cloud API Gateway.
	//
	// > Either `apiGatewayId` or `name` must be specified.
	FolderId *string `pulumi:"folderId"`
	// Yandex Cloud API Gateway name used to define api gateway.
	Name *string `pulumi:"name"`
	// A set of values for variables in gateway specification.
	Variables map[string]string `pulumi:"variables"`
}

// A collection of values returned by getApiGateway.
type LookupApiGatewayResult struct {
	ApiGatewayId *string `pulumi:"apiGatewayId"`
	// Canary release settings of gateway.
	Canary *GetApiGatewayCanary `pulumi:"canary"`
	// Gateway connectivity. If specified the gateway will be attached to specified network.
	Connectivity *GetApiGatewayConnectivity `pulumi:"connectivity"`
	// Creation timestamp of the Yandex Cloud API Gateway.
	CreatedAt string `pulumi:"createdAt"`
	// Set of custom domains attached to Yandex API Gateway. Each set item has the following properties: `domainId`, `fqdn`, `certificateId`.
	CustomDomains []GetApiGatewayCustomDomain `pulumi:"customDomains"`
	// Description of the Yandex Cloud API Gateway.
	Description string `pulumi:"description"`
	// Default domain for the Yandex API Gateway.
	Domain string `pulumi:"domain"`
	// Execution timeout in seconds for the Yandex Cloud API Gateway.
	ExecutionTimeout string  `pulumi:"executionTimeout"`
	FolderId         *string `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A set of key/value label pairs to assign to the Yandex Cloud API Gateway.
	Labels     map[string]string `pulumi:"labels"`
	LogGroupId string            `pulumi:"logGroupId"`
	// Options for logging from Yandex Cloud Function.
	LogOptions []GetApiGatewayLogOption `pulumi:"logOptions"`
	Name       *string                  `pulumi:"name"`
	// Status of the Yandex API Gateway.
	Status string `pulumi:"status"`
	// (**DEPRECATED**, use `customDomains` instead) Set of user domains attached to Yandex API Gateway.
	//
	// Deprecated: The 'user_domains' field has been deprecated. Please use 'custom_domains' instead.
	UserDomains []string `pulumi:"userDomains"`
	// A set of values for variables in gateway specification.
	Variables map[string]string `pulumi:"variables"`
}

func LookupApiGatewayOutput(ctx *pulumi.Context, args LookupApiGatewayOutputArgs, opts ...pulumi.InvokeOption) LookupApiGatewayResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupApiGatewayResultOutput, error) {
			args := v.(LookupApiGatewayArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getApiGateway:getApiGateway", args, LookupApiGatewayResultOutput{}, options).(LookupApiGatewayResultOutput), nil
		}).(LookupApiGatewayResultOutput)
}

// A collection of arguments for invoking getApiGateway.
type LookupApiGatewayOutputArgs struct {
	// Yandex Cloud API Gateway id used to define api gateway.
	ApiGatewayId pulumi.StringPtrInput `pulumi:"apiGatewayId"`
	// Canary release settings of gateway.
	Canary GetApiGatewayCanaryPtrInput `pulumi:"canary"`
	// Gateway connectivity. If specified the gateway will be attached to specified network.
	Connectivity GetApiGatewayConnectivityPtrInput `pulumi:"connectivity"`
	// Set of custom domains attached to Yandex API Gateway. Each set item has the following properties: `domainId`, `fqdn`, `certificateId`.
	CustomDomains GetApiGatewayCustomDomainArrayInput `pulumi:"customDomains"`
	// Execution timeout in seconds for the Yandex Cloud API Gateway.
	ExecutionTimeout pulumi.StringPtrInput `pulumi:"executionTimeout"`
	// Folder ID for the Yandex Cloud API Gateway.
	//
	// > Either `apiGatewayId` or `name` must be specified.
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	// Yandex Cloud API Gateway name used to define api gateway.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// A set of values for variables in gateway specification.
	Variables pulumi.StringMapInput `pulumi:"variables"`
}

func (LookupApiGatewayOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApiGatewayArgs)(nil)).Elem()
}

// A collection of values returned by getApiGateway.
type LookupApiGatewayResultOutput struct{ *pulumi.OutputState }

func (LookupApiGatewayResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApiGatewayResult)(nil)).Elem()
}

func (o LookupApiGatewayResultOutput) ToLookupApiGatewayResultOutput() LookupApiGatewayResultOutput {
	return o
}

func (o LookupApiGatewayResultOutput) ToLookupApiGatewayResultOutputWithContext(ctx context.Context) LookupApiGatewayResultOutput {
	return o
}

func (o LookupApiGatewayResultOutput) ApiGatewayId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) *string { return v.ApiGatewayId }).(pulumi.StringPtrOutput)
}

// Canary release settings of gateway.
func (o LookupApiGatewayResultOutput) Canary() GetApiGatewayCanaryPtrOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) *GetApiGatewayCanary { return v.Canary }).(GetApiGatewayCanaryPtrOutput)
}

// Gateway connectivity. If specified the gateway will be attached to specified network.
func (o LookupApiGatewayResultOutput) Connectivity() GetApiGatewayConnectivityPtrOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) *GetApiGatewayConnectivity { return v.Connectivity }).(GetApiGatewayConnectivityPtrOutput)
}

// Creation timestamp of the Yandex Cloud API Gateway.
func (o LookupApiGatewayResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Set of custom domains attached to Yandex API Gateway. Each set item has the following properties: `domainId`, `fqdn`, `certificateId`.
func (o LookupApiGatewayResultOutput) CustomDomains() GetApiGatewayCustomDomainArrayOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) []GetApiGatewayCustomDomain { return v.CustomDomains }).(GetApiGatewayCustomDomainArrayOutput)
}

// Description of the Yandex Cloud API Gateway.
func (o LookupApiGatewayResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) string { return v.Description }).(pulumi.StringOutput)
}

// Default domain for the Yandex API Gateway.
func (o LookupApiGatewayResultOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) string { return v.Domain }).(pulumi.StringOutput)
}

// Execution timeout in seconds for the Yandex Cloud API Gateway.
func (o LookupApiGatewayResultOutput) ExecutionTimeout() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) string { return v.ExecutionTimeout }).(pulumi.StringOutput)
}

func (o LookupApiGatewayResultOutput) FolderId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) *string { return v.FolderId }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupApiGatewayResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) string { return v.Id }).(pulumi.StringOutput)
}

// A set of key/value label pairs to assign to the Yandex Cloud API Gateway.
func (o LookupApiGatewayResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupApiGatewayResultOutput) LogGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) string { return v.LogGroupId }).(pulumi.StringOutput)
}

// Options for logging from Yandex Cloud Function.
func (o LookupApiGatewayResultOutput) LogOptions() GetApiGatewayLogOptionArrayOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) []GetApiGatewayLogOption { return v.LogOptions }).(GetApiGatewayLogOptionArrayOutput)
}

func (o LookupApiGatewayResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// Status of the Yandex API Gateway.
func (o LookupApiGatewayResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) string { return v.Status }).(pulumi.StringOutput)
}

// (**DEPRECATED**, use `customDomains` instead) Set of user domains attached to Yandex API Gateway.
//
// Deprecated: The 'user_domains' field has been deprecated. Please use 'custom_domains' instead.
func (o LookupApiGatewayResultOutput) UserDomains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) []string { return v.UserDomains }).(pulumi.StringArrayOutput)
}

// A set of values for variables in gateway specification.
func (o LookupApiGatewayResultOutput) Variables() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupApiGatewayResult) map[string]string { return v.Variables }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupApiGatewayResultOutput{})
}
