// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/agorobets/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Application Load Balancer. For more information, see [Yandex Cloud Application Load Balancer](https://yandex.cloud/docs/application-load-balancer/quickstart).
//
// ## Example Usage
//
// {{ tffile "examples/alb_load_balancer/d_alb_load_balancer_1.tf" }}
//
// This data source is used to define [Application Load Balancer](https://yandex.cloud/docs/application-load-balancer/concepts/application-load-balancer) that can be used by other resources.
func LookupAlbLoadBalancer(ctx *pulumi.Context, args *LookupAlbLoadBalancerArgs, opts ...pulumi.InvokeOption) (*LookupAlbLoadBalancerResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAlbLoadBalancerResult
	err := ctx.Invoke("yandex:index/getAlbLoadBalancer:getAlbLoadBalancer", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAlbLoadBalancer.
type LookupAlbLoadBalancerArgs struct {
	// Load Balancer ID.
	LoadBalancerId *string `pulumi:"loadBalancerId"`
	// Name of the Load Balancer.
	//
	// > One of `loadBalancerId` or `name` should be specified.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getAlbLoadBalancer.
type LookupAlbLoadBalancerResult struct {
	// Allocation zones for the Load Balancer instance. The structure is documented below.
	AllocationPolicies []GetAlbLoadBalancerAllocationPolicy `pulumi:"allocationPolicies"`
	// The Load Balancer creation timestamp.
	CreatedAt string `pulumi:"createdAt"`
	// An optional description of the Load Balancer.
	Description string `pulumi:"description"`
	// The ID of the folder to which the resource belongs. If omitted, the provider folder is used.
	FolderId string `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Labels to assign to this Load Balancer. A list of key/value pairs.
	Labels map[string]string `pulumi:"labels"`
	// List of listeners for the Load Balancer. The structure is documented below.
	Listeners      []GetAlbLoadBalancerListener `pulumi:"listeners"`
	LoadBalancerId string                       `pulumi:"loadBalancerId"`
	// (Optional) Cloud Logging group ID to send logs to. Leave empty to use the balancer folder default log group.
	LogGroupId string `pulumi:"logGroupId"`
	// Cloud Logging settings. The structure is documented below.
	LogOptions []GetAlbLoadBalancerLogOption `pulumi:"logOptions"`
	// name of SNI match.
	Name string `pulumi:"name"`
	// ID of the network that the Load Balancer is located at.
	NetworkId string `pulumi:"networkId"`
	// ID of the region that the Load Balancer is located at.
	RegionId string `pulumi:"regionId"`
	// A list of ID's of security groups attached to the Load Balancer.
	SecurityGroupIds []string `pulumi:"securityGroupIds"`
	// Status of the Load Balancer.
	Status string `pulumi:"status"`
}

func LookupAlbLoadBalancerOutput(ctx *pulumi.Context, args LookupAlbLoadBalancerOutputArgs, opts ...pulumi.InvokeOption) LookupAlbLoadBalancerResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupAlbLoadBalancerResultOutput, error) {
			args := v.(LookupAlbLoadBalancerArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getAlbLoadBalancer:getAlbLoadBalancer", args, LookupAlbLoadBalancerResultOutput{}, options).(LookupAlbLoadBalancerResultOutput), nil
		}).(LookupAlbLoadBalancerResultOutput)
}

// A collection of arguments for invoking getAlbLoadBalancer.
type LookupAlbLoadBalancerOutputArgs struct {
	// Load Balancer ID.
	LoadBalancerId pulumi.StringPtrInput `pulumi:"loadBalancerId"`
	// Name of the Load Balancer.
	//
	// > One of `loadBalancerId` or `name` should be specified.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupAlbLoadBalancerOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAlbLoadBalancerArgs)(nil)).Elem()
}

// A collection of values returned by getAlbLoadBalancer.
type LookupAlbLoadBalancerResultOutput struct{ *pulumi.OutputState }

func (LookupAlbLoadBalancerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAlbLoadBalancerResult)(nil)).Elem()
}

func (o LookupAlbLoadBalancerResultOutput) ToLookupAlbLoadBalancerResultOutput() LookupAlbLoadBalancerResultOutput {
	return o
}

func (o LookupAlbLoadBalancerResultOutput) ToLookupAlbLoadBalancerResultOutputWithContext(ctx context.Context) LookupAlbLoadBalancerResultOutput {
	return o
}

// Allocation zones for the Load Balancer instance. The structure is documented below.
func (o LookupAlbLoadBalancerResultOutput) AllocationPolicies() GetAlbLoadBalancerAllocationPolicyArrayOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) []GetAlbLoadBalancerAllocationPolicy { return v.AllocationPolicies }).(GetAlbLoadBalancerAllocationPolicyArrayOutput)
}

// The Load Balancer creation timestamp.
func (o LookupAlbLoadBalancerResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// An optional description of the Load Balancer.
func (o LookupAlbLoadBalancerResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) string { return v.Description }).(pulumi.StringOutput)
}

// The ID of the folder to which the resource belongs. If omitted, the provider folder is used.
func (o LookupAlbLoadBalancerResultOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) string { return v.FolderId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupAlbLoadBalancerResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) string { return v.Id }).(pulumi.StringOutput)
}

// Labels to assign to this Load Balancer. A list of key/value pairs.
func (o LookupAlbLoadBalancerResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

// List of listeners for the Load Balancer. The structure is documented below.
func (o LookupAlbLoadBalancerResultOutput) Listeners() GetAlbLoadBalancerListenerArrayOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) []GetAlbLoadBalancerListener { return v.Listeners }).(GetAlbLoadBalancerListenerArrayOutput)
}

func (o LookupAlbLoadBalancerResultOutput) LoadBalancerId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) string { return v.LoadBalancerId }).(pulumi.StringOutput)
}

// (Optional) Cloud Logging group ID to send logs to. Leave empty to use the balancer folder default log group.
func (o LookupAlbLoadBalancerResultOutput) LogGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) string { return v.LogGroupId }).(pulumi.StringOutput)
}

// Cloud Logging settings. The structure is documented below.
func (o LookupAlbLoadBalancerResultOutput) LogOptions() GetAlbLoadBalancerLogOptionArrayOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) []GetAlbLoadBalancerLogOption { return v.LogOptions }).(GetAlbLoadBalancerLogOptionArrayOutput)
}

// name of SNI match.
func (o LookupAlbLoadBalancerResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) string { return v.Name }).(pulumi.StringOutput)
}

// ID of the network that the Load Balancer is located at.
func (o LookupAlbLoadBalancerResultOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) string { return v.NetworkId }).(pulumi.StringOutput)
}

// ID of the region that the Load Balancer is located at.
func (o LookupAlbLoadBalancerResultOutput) RegionId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) string { return v.RegionId }).(pulumi.StringOutput)
}

// A list of ID's of security groups attached to the Load Balancer.
func (o LookupAlbLoadBalancerResultOutput) SecurityGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) []string { return v.SecurityGroupIds }).(pulumi.StringArrayOutput)
}

// Status of the Load Balancer.
func (o LookupAlbLoadBalancerResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlbLoadBalancerResult) string { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAlbLoadBalancerResultOutput{})
}
