// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/agorobets/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Compute GPU cluster. For more information, see [the official documentation](https://cloud.yandex.com/docs/compute/concepts/gpu-cluster).
//
// ## Example Usage
//
// {{ tffile "examples/compute_gpu_cluster/d_compute_gpu_cluster_1.tf" }}
func LookupComputeGpuCluster(ctx *pulumi.Context, args *LookupComputeGpuClusterArgs, opts ...pulumi.InvokeOption) (*LookupComputeGpuClusterResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupComputeGpuClusterResult
	err := ctx.Invoke("yandex:index/getComputeGpuCluster:getComputeGpuCluster", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getComputeGpuCluster.
type LookupComputeGpuClusterArgs struct {
	// ID of the folder that the GPU cluster belongs to.
	FolderId *string `pulumi:"folderId"`
	// ID of the GPU cluster.
	GpuClusterId *string `pulumi:"gpuClusterId"`
	// Name of the GPU cluster.
	//
	// > One of `gpuClusterId` or `name` should be specified.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getComputeGpuCluster.
type LookupComputeGpuClusterResult struct {
	// Creation timestamp.
	CreatedAt string `pulumi:"createdAt"`
	// Optional description of the GPU cluster.
	Description string `pulumi:"description"`
	// ID of the folder that the GPU cluster belongs to.
	FolderId     string `pulumi:"folderId"`
	GpuClusterId string `pulumi:"gpuClusterId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// type of interconnect used between nodes in GPU cluster.
	InterconnectType string `pulumi:"interconnectType"`
	// GPU cluster labels as `key:value` pairs. For details about the concept, see [documentation](https://cloud.yandex.com/docs/overview/concepts/services#labels).
	Labels map[string]string `pulumi:"labels"`
	Name   string            `pulumi:"name"`
	// Current status of the GPU cluster.
	Status string `pulumi:"status"`
	// ID of the zone where the GPU cluster resides.
	Zone string `pulumi:"zone"`
}

func LookupComputeGpuClusterOutput(ctx *pulumi.Context, args LookupComputeGpuClusterOutputArgs, opts ...pulumi.InvokeOption) LookupComputeGpuClusterResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupComputeGpuClusterResultOutput, error) {
			args := v.(LookupComputeGpuClusterArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getComputeGpuCluster:getComputeGpuCluster", args, LookupComputeGpuClusterResultOutput{}, options).(LookupComputeGpuClusterResultOutput), nil
		}).(LookupComputeGpuClusterResultOutput)
}

// A collection of arguments for invoking getComputeGpuCluster.
type LookupComputeGpuClusterOutputArgs struct {
	// ID of the folder that the GPU cluster belongs to.
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	// ID of the GPU cluster.
	GpuClusterId pulumi.StringPtrInput `pulumi:"gpuClusterId"`
	// Name of the GPU cluster.
	//
	// > One of `gpuClusterId` or `name` should be specified.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupComputeGpuClusterOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupComputeGpuClusterArgs)(nil)).Elem()
}

// A collection of values returned by getComputeGpuCluster.
type LookupComputeGpuClusterResultOutput struct{ *pulumi.OutputState }

func (LookupComputeGpuClusterResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupComputeGpuClusterResult)(nil)).Elem()
}

func (o LookupComputeGpuClusterResultOutput) ToLookupComputeGpuClusterResultOutput() LookupComputeGpuClusterResultOutput {
	return o
}

func (o LookupComputeGpuClusterResultOutput) ToLookupComputeGpuClusterResultOutputWithContext(ctx context.Context) LookupComputeGpuClusterResultOutput {
	return o
}

// Creation timestamp.
func (o LookupComputeGpuClusterResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeGpuClusterResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Optional description of the GPU cluster.
func (o LookupComputeGpuClusterResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeGpuClusterResult) string { return v.Description }).(pulumi.StringOutput)
}

// ID of the folder that the GPU cluster belongs to.
func (o LookupComputeGpuClusterResultOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeGpuClusterResult) string { return v.FolderId }).(pulumi.StringOutput)
}

func (o LookupComputeGpuClusterResultOutput) GpuClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeGpuClusterResult) string { return v.GpuClusterId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupComputeGpuClusterResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeGpuClusterResult) string { return v.Id }).(pulumi.StringOutput)
}

// type of interconnect used between nodes in GPU cluster.
func (o LookupComputeGpuClusterResultOutput) InterconnectType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeGpuClusterResult) string { return v.InterconnectType }).(pulumi.StringOutput)
}

// GPU cluster labels as `key:value` pairs. For details about the concept, see [documentation](https://cloud.yandex.com/docs/overview/concepts/services#labels).
func (o LookupComputeGpuClusterResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupComputeGpuClusterResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupComputeGpuClusterResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeGpuClusterResult) string { return v.Name }).(pulumi.StringOutput)
}

// Current status of the GPU cluster.
func (o LookupComputeGpuClusterResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeGpuClusterResult) string { return v.Status }).(pulumi.StringOutput)
}

// ID of the zone where the GPU cluster resides.
func (o LookupComputeGpuClusterResultOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeGpuClusterResult) string { return v.Zone }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupComputeGpuClusterResultOutput{})
}
