// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/agorobets/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Certificate Manager Certificate. For more information, see [the official documentation](https://yandex.cloud/docs/certificate-manager/concepts/).
//
// ## Example Usage
//
// {{ tffile "examples/cm_certificate/d_cm_certificate_1.tf" }}
//
// This data source is used to define [Certificate Manager Certificate](https://yandex.cloud/docs/certificate-manager/concepts/) that can be used by other resources. Can also be used to wait for certificate validation.
//
// {{ tffile "examples/cm_certificate/d_cm_certificate_2.tf" }}
func LookupCmCertificate(ctx *pulumi.Context, args *LookupCmCertificateArgs, opts ...pulumi.InvokeOption) (*LookupCmCertificateResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupCmCertificateResult
	err := ctx.Invoke("yandex:index/getCmCertificate:getCmCertificate", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCmCertificate.
type LookupCmCertificateArgs struct {
	// Certificate Id.
	CertificateId *string `pulumi:"certificateId"`
	// Certificate description.
	Description *string `pulumi:"description"`
	// Folder that the resource belongs to. If value is omitted, the default provider folder is used.
	FolderId *string `pulumi:"folderId"`
	// Labels to assign to this certificate.
	Labels map[string]string `pulumi:"labels"`
	// Name of the Certificate.
	Name *string `pulumi:"name"`
	// If `true`, the operation won't be completed while the certificate is in `VALIDATING`.
	//
	// > One of `certificateId` or `name` should be specified.
	WaitValidation *bool `pulumi:"waitValidation"`
}

// A collection of values returned by getCmCertificate.
type LookupCmCertificateResult struct {
	CertificateId string `pulumi:"certificateId"`
	// Array of challenges. Structure is documented below.
	Challenges []GetCmCertificateChallenge `pulumi:"challenges"`
	// Time the challenge was created.
	CreatedAt          string `pulumi:"createdAt"`
	DeletionProtection bool   `pulumi:"deletionProtection"`
	// Certificate description.
	Description string   `pulumi:"description"`
	Domains     []string `pulumi:"domains"`
	FolderId    string   `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Certificate issue timestamp.
	IssuedAt string `pulumi:"issuedAt"`
	// Certificate issuer.
	Issuer string `pulumi:"issuer"`
	// Labels to assign to this certificate.
	Labels map[string]string `pulumi:"labels"`
	Name   string            `pulumi:"name"`
	// Certificate end valid period.
	NotAfter string `pulumi:"notAfter"`
	// Certificate start valid period.
	NotBefore string `pulumi:"notBefore"`
	// Certificate serial number.
	Serial string `pulumi:"serial"`
	// Certificate status: `"VALIDATING"`, `"INVALID"`, `"ISSUED"`, `"REVOKED"`, `"RENEWING"` or `"RENEWAL_FAILED"`.
	Status string `pulumi:"status"`
	// Certificate subject.
	Subject string `pulumi:"subject"`
	// Challenge type `"DNS"` or `"HTTP"`.
	Type string `pulumi:"type"`
	// Last time the challenge was updated.
	UpdatedAt      string `pulumi:"updatedAt"`
	WaitValidation *bool  `pulumi:"waitValidation"`
}

func LookupCmCertificateOutput(ctx *pulumi.Context, args LookupCmCertificateOutputArgs, opts ...pulumi.InvokeOption) LookupCmCertificateResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupCmCertificateResultOutput, error) {
			args := v.(LookupCmCertificateArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getCmCertificate:getCmCertificate", args, LookupCmCertificateResultOutput{}, options).(LookupCmCertificateResultOutput), nil
		}).(LookupCmCertificateResultOutput)
}

// A collection of arguments for invoking getCmCertificate.
type LookupCmCertificateOutputArgs struct {
	// Certificate Id.
	CertificateId pulumi.StringPtrInput `pulumi:"certificateId"`
	// Certificate description.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// Folder that the resource belongs to. If value is omitted, the default provider folder is used.
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	// Labels to assign to this certificate.
	Labels pulumi.StringMapInput `pulumi:"labels"`
	// Name of the Certificate.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// If `true`, the operation won't be completed while the certificate is in `VALIDATING`.
	//
	// > One of `certificateId` or `name` should be specified.
	WaitValidation pulumi.BoolPtrInput `pulumi:"waitValidation"`
}

func (LookupCmCertificateOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCmCertificateArgs)(nil)).Elem()
}

// A collection of values returned by getCmCertificate.
type LookupCmCertificateResultOutput struct{ *pulumi.OutputState }

func (LookupCmCertificateResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCmCertificateResult)(nil)).Elem()
}

func (o LookupCmCertificateResultOutput) ToLookupCmCertificateResultOutput() LookupCmCertificateResultOutput {
	return o
}

func (o LookupCmCertificateResultOutput) ToLookupCmCertificateResultOutputWithContext(ctx context.Context) LookupCmCertificateResultOutput {
	return o
}

func (o LookupCmCertificateResultOutput) CertificateId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.CertificateId }).(pulumi.StringOutput)
}

// Array of challenges. Structure is documented below.
func (o LookupCmCertificateResultOutput) Challenges() GetCmCertificateChallengeArrayOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) []GetCmCertificateChallenge { return v.Challenges }).(GetCmCertificateChallengeArrayOutput)
}

// Time the challenge was created.
func (o LookupCmCertificateResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupCmCertificateResultOutput) DeletionProtection() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) bool { return v.DeletionProtection }).(pulumi.BoolOutput)
}

// Certificate description.
func (o LookupCmCertificateResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupCmCertificateResultOutput) Domains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) []string { return v.Domains }).(pulumi.StringArrayOutput)
}

func (o LookupCmCertificateResultOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.FolderId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupCmCertificateResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.Id }).(pulumi.StringOutput)
}

// Certificate issue timestamp.
func (o LookupCmCertificateResultOutput) IssuedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.IssuedAt }).(pulumi.StringOutput)
}

// Certificate issuer.
func (o LookupCmCertificateResultOutput) Issuer() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.Issuer }).(pulumi.StringOutput)
}

// Labels to assign to this certificate.
func (o LookupCmCertificateResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupCmCertificateResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.Name }).(pulumi.StringOutput)
}

// Certificate end valid period.
func (o LookupCmCertificateResultOutput) NotAfter() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.NotAfter }).(pulumi.StringOutput)
}

// Certificate start valid period.
func (o LookupCmCertificateResultOutput) NotBefore() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.NotBefore }).(pulumi.StringOutput)
}

// Certificate serial number.
func (o LookupCmCertificateResultOutput) Serial() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.Serial }).(pulumi.StringOutput)
}

// Certificate status: `"VALIDATING"`, `"INVALID"`, `"ISSUED"`, `"REVOKED"`, `"RENEWING"` or `"RENEWAL_FAILED"`.
func (o LookupCmCertificateResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.Status }).(pulumi.StringOutput)
}

// Certificate subject.
func (o LookupCmCertificateResultOutput) Subject() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.Subject }).(pulumi.StringOutput)
}

// Challenge type `"DNS"` or `"HTTP"`.
func (o LookupCmCertificateResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.Type }).(pulumi.StringOutput)
}

// Last time the challenge was updated.
func (o LookupCmCertificateResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func (o LookupCmCertificateResultOutput) WaitValidation() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupCmCertificateResult) *bool { return v.WaitValidation }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCmCertificateResultOutput{})
}
