// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/agorobets/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Compute filesystem. For more information, see [the official documentation](https://cloud.yandex.com/docs/compute/concepts/filesystem).
//
// ## Example Usage
//
// {{ tffile "examples/compute_filesystem/d_compute_filesystem_1.tf" }}
func LookupComputeFilesystem(ctx *pulumi.Context, args *LookupComputeFilesystemArgs, opts ...pulumi.InvokeOption) (*LookupComputeFilesystemResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupComputeFilesystemResult
	err := ctx.Invoke("yandex:index/getComputeFilesystem:getComputeFilesystem", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getComputeFilesystem.
type LookupComputeFilesystemArgs struct {
	FilesystemId *string `pulumi:"filesystemId"`
	// ID of the folder that the filesystem belongs to.
	FolderId *string `pulumi:"folderId"`
	// Name of the filesystem.
	//
	// > One of `filesystemId` or `name` should be specified.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getComputeFilesystem.
type LookupComputeFilesystemResult struct {
	// The block size of the filesystem in bytes.
	BlockSize int `pulumi:"blockSize"`
	// Creation timestamp.
	CreatedAt string `pulumi:"createdAt"`
	// Optional description of the filesystem.
	Description  string `pulumi:"description"`
	FilesystemId string `pulumi:"filesystemId"`
	// ID of the folder that the filesystem belongs to.
	FolderId string `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Filesystem labels as `key:value` pairs. For details about the concept, see [documentation](https://cloud.yandex.com/docs/overview/concepts/services#labels).
	Labels map[string]string `pulumi:"labels"`
	Name   string            `pulumi:"name"`
	// Size of the filesystem, specified in Gb.
	Size int `pulumi:"size"`
	// Current status of the filesystem.
	Status string `pulumi:"status"`
	// ID of the filesystem type.
	Type string `pulumi:"type"`
	// ID of the zone where the filesystem resides.
	Zone string `pulumi:"zone"`
}

func LookupComputeFilesystemOutput(ctx *pulumi.Context, args LookupComputeFilesystemOutputArgs, opts ...pulumi.InvokeOption) LookupComputeFilesystemResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupComputeFilesystemResultOutput, error) {
			args := v.(LookupComputeFilesystemArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getComputeFilesystem:getComputeFilesystem", args, LookupComputeFilesystemResultOutput{}, options).(LookupComputeFilesystemResultOutput), nil
		}).(LookupComputeFilesystemResultOutput)
}

// A collection of arguments for invoking getComputeFilesystem.
type LookupComputeFilesystemOutputArgs struct {
	FilesystemId pulumi.StringPtrInput `pulumi:"filesystemId"`
	// ID of the folder that the filesystem belongs to.
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	// Name of the filesystem.
	//
	// > One of `filesystemId` or `name` should be specified.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupComputeFilesystemOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupComputeFilesystemArgs)(nil)).Elem()
}

// A collection of values returned by getComputeFilesystem.
type LookupComputeFilesystemResultOutput struct{ *pulumi.OutputState }

func (LookupComputeFilesystemResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupComputeFilesystemResult)(nil)).Elem()
}

func (o LookupComputeFilesystemResultOutput) ToLookupComputeFilesystemResultOutput() LookupComputeFilesystemResultOutput {
	return o
}

func (o LookupComputeFilesystemResultOutput) ToLookupComputeFilesystemResultOutputWithContext(ctx context.Context) LookupComputeFilesystemResultOutput {
	return o
}

// The block size of the filesystem in bytes.
func (o LookupComputeFilesystemResultOutput) BlockSize() pulumi.IntOutput {
	return o.ApplyT(func(v LookupComputeFilesystemResult) int { return v.BlockSize }).(pulumi.IntOutput)
}

// Creation timestamp.
func (o LookupComputeFilesystemResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeFilesystemResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Optional description of the filesystem.
func (o LookupComputeFilesystemResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeFilesystemResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupComputeFilesystemResultOutput) FilesystemId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeFilesystemResult) string { return v.FilesystemId }).(pulumi.StringOutput)
}

// ID of the folder that the filesystem belongs to.
func (o LookupComputeFilesystemResultOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeFilesystemResult) string { return v.FolderId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupComputeFilesystemResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeFilesystemResult) string { return v.Id }).(pulumi.StringOutput)
}

// Filesystem labels as `key:value` pairs. For details about the concept, see [documentation](https://cloud.yandex.com/docs/overview/concepts/services#labels).
func (o LookupComputeFilesystemResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupComputeFilesystemResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupComputeFilesystemResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeFilesystemResult) string { return v.Name }).(pulumi.StringOutput)
}

// Size of the filesystem, specified in Gb.
func (o LookupComputeFilesystemResultOutput) Size() pulumi.IntOutput {
	return o.ApplyT(func(v LookupComputeFilesystemResult) int { return v.Size }).(pulumi.IntOutput)
}

// Current status of the filesystem.
func (o LookupComputeFilesystemResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeFilesystemResult) string { return v.Status }).(pulumi.StringOutput)
}

// ID of the filesystem type.
func (o LookupComputeFilesystemResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeFilesystemResult) string { return v.Type }).(pulumi.StringOutput)
}

// ID of the zone where the filesystem resides.
func (o LookupComputeFilesystemResultOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComputeFilesystemResult) string { return v.Zone }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupComputeFilesystemResultOutput{})
}
