// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/agorobets/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Cloud Function Trigger. For more information about Yandex Cloud Functions, see [Yandex Cloud Functions](https://cloud.yandex.com/docs/functions/).
//
// ## Example Usage
//
// {{ tffile "examples/function_trigger/d_function_trigger_1.tf" }}
//
// This data source is used to define [Yandex Cloud Functions Trigger](https://cloud.yandex.com/docs/functions/concepts/trigger) that can be used by other resources.
func LookupFunctionTrigger(ctx *pulumi.Context, args *LookupFunctionTriggerArgs, opts ...pulumi.InvokeOption) (*LookupFunctionTriggerResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFunctionTriggerResult
	err := ctx.Invoke("yandex:index/getFunctionTrigger:getFunctionTrigger", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFunctionTrigger.
type LookupFunctionTriggerArgs struct {
	// Folder ID for the Yandex Cloud Functions Trigger
	//
	// > Either `triggerId` or `name` must be specified.
	FolderId *string `pulumi:"folderId"`
	// Yandex Cloud Functions Trigger name used to define trigger
	Name *string `pulumi:"name"`
	// Yandex Cloud Functions Trigger id used to define trigger
	TriggerId *string `pulumi:"triggerId"`
}

// A collection of values returned by getFunctionTrigger.
type LookupFunctionTriggerResult struct {
	ContainerRegistries []GetFunctionTriggerContainerRegistry `pulumi:"containerRegistries"`
	Containers          []GetFunctionTriggerContainer         `pulumi:"containers"`
	// Creation timestamp of the Yandex Cloud Functions Trigger
	CreatedAt   string                         `pulumi:"createdAt"`
	DataStreams []GetFunctionTriggerDataStream `pulumi:"dataStreams"`
	// Description of the Yandex Cloud Functions Trigger
	Description string `pulumi:"description"`
	// Dead Letter Queue settings definition for Yandex Cloud Functions Trigger
	Dlqs []GetFunctionTriggerDlq `pulumi:"dlqs"`
	// Folder ID for the Yandex Cloud Functions Trigger
	FolderId *string `pulumi:"folderId"`
	// [Yandex Cloud Function](https://cloud.yandex.com/docs/functions/concepts/function) settings definition for Yandex Cloud Functions Trigger
	Functions []GetFunctionTriggerFunction `pulumi:"functions"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// [IoT](https://cloud.yandex.com/docs/functions/concepts/trigger/iot-core-trigger) settings definition for Yandex Cloud Functions Trigger, if present
	Iots []GetFunctionTriggerIot `pulumi:"iots"`
	// A set of key/value label pairs to assign to the Yandex Cloud Functions Trigger
	Labels    map[string]string            `pulumi:"labels"`
	LogGroups []GetFunctionTriggerLogGroup `pulumi:"logGroups"`
	Loggings  []GetFunctionTriggerLogging  `pulumi:"loggings"`
	Mails     []GetFunctionTriggerMail     `pulumi:"mails"`
	// [Message Queue](https://cloud.yandex.com/docs/functions/concepts/trigger/ymq-trigger) settings definition for Yandex Cloud Functions Trigger, if present
	MessageQueues []GetFunctionTriggerMessageQueue `pulumi:"messageQueues"`
	Name          *string                          `pulumi:"name"`
	// [Object Storage](https://cloud.yandex.com/docs/functions/concepts/trigger/os-trigger) settings definition for Yandex Cloud Functions Trigger, if present
	ObjectStorages []GetFunctionTriggerObjectStorage `pulumi:"objectStorages"`
	// [Timer](https://cloud.yandex.com/docs/functions/concepts/trigger/timer) settings definition for Yandex Cloud Functions Trigger, if present
	Timers    []GetFunctionTriggerTimer `pulumi:"timers"`
	TriggerId *string                   `pulumi:"triggerId"`
}

func LookupFunctionTriggerOutput(ctx *pulumi.Context, args LookupFunctionTriggerOutputArgs, opts ...pulumi.InvokeOption) LookupFunctionTriggerResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupFunctionTriggerResultOutput, error) {
			args := v.(LookupFunctionTriggerArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getFunctionTrigger:getFunctionTrigger", args, LookupFunctionTriggerResultOutput{}, options).(LookupFunctionTriggerResultOutput), nil
		}).(LookupFunctionTriggerResultOutput)
}

// A collection of arguments for invoking getFunctionTrigger.
type LookupFunctionTriggerOutputArgs struct {
	// Folder ID for the Yandex Cloud Functions Trigger
	//
	// > Either `triggerId` or `name` must be specified.
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	// Yandex Cloud Functions Trigger name used to define trigger
	Name pulumi.StringPtrInput `pulumi:"name"`
	// Yandex Cloud Functions Trigger id used to define trigger
	TriggerId pulumi.StringPtrInput `pulumi:"triggerId"`
}

func (LookupFunctionTriggerOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFunctionTriggerArgs)(nil)).Elem()
}

// A collection of values returned by getFunctionTrigger.
type LookupFunctionTriggerResultOutput struct{ *pulumi.OutputState }

func (LookupFunctionTriggerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFunctionTriggerResult)(nil)).Elem()
}

func (o LookupFunctionTriggerResultOutput) ToLookupFunctionTriggerResultOutput() LookupFunctionTriggerResultOutput {
	return o
}

func (o LookupFunctionTriggerResultOutput) ToLookupFunctionTriggerResultOutputWithContext(ctx context.Context) LookupFunctionTriggerResultOutput {
	return o
}

func (o LookupFunctionTriggerResultOutput) ContainerRegistries() GetFunctionTriggerContainerRegistryArrayOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) []GetFunctionTriggerContainerRegistry {
		return v.ContainerRegistries
	}).(GetFunctionTriggerContainerRegistryArrayOutput)
}

func (o LookupFunctionTriggerResultOutput) Containers() GetFunctionTriggerContainerArrayOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) []GetFunctionTriggerContainer { return v.Containers }).(GetFunctionTriggerContainerArrayOutput)
}

// Creation timestamp of the Yandex Cloud Functions Trigger
func (o LookupFunctionTriggerResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupFunctionTriggerResultOutput) DataStreams() GetFunctionTriggerDataStreamArrayOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) []GetFunctionTriggerDataStream { return v.DataStreams }).(GetFunctionTriggerDataStreamArrayOutput)
}

// Description of the Yandex Cloud Functions Trigger
func (o LookupFunctionTriggerResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) string { return v.Description }).(pulumi.StringOutput)
}

// Dead Letter Queue settings definition for Yandex Cloud Functions Trigger
func (o LookupFunctionTriggerResultOutput) Dlqs() GetFunctionTriggerDlqArrayOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) []GetFunctionTriggerDlq { return v.Dlqs }).(GetFunctionTriggerDlqArrayOutput)
}

// Folder ID for the Yandex Cloud Functions Trigger
func (o LookupFunctionTriggerResultOutput) FolderId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) *string { return v.FolderId }).(pulumi.StringPtrOutput)
}

// [Yandex Cloud Function](https://cloud.yandex.com/docs/functions/concepts/function) settings definition for Yandex Cloud Functions Trigger
func (o LookupFunctionTriggerResultOutput) Functions() GetFunctionTriggerFunctionArrayOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) []GetFunctionTriggerFunction { return v.Functions }).(GetFunctionTriggerFunctionArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupFunctionTriggerResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) string { return v.Id }).(pulumi.StringOutput)
}

// [IoT](https://cloud.yandex.com/docs/functions/concepts/trigger/iot-core-trigger) settings definition for Yandex Cloud Functions Trigger, if present
func (o LookupFunctionTriggerResultOutput) Iots() GetFunctionTriggerIotArrayOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) []GetFunctionTriggerIot { return v.Iots }).(GetFunctionTriggerIotArrayOutput)
}

// A set of key/value label pairs to assign to the Yandex Cloud Functions Trigger
func (o LookupFunctionTriggerResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupFunctionTriggerResultOutput) LogGroups() GetFunctionTriggerLogGroupArrayOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) []GetFunctionTriggerLogGroup { return v.LogGroups }).(GetFunctionTriggerLogGroupArrayOutput)
}

func (o LookupFunctionTriggerResultOutput) Loggings() GetFunctionTriggerLoggingArrayOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) []GetFunctionTriggerLogging { return v.Loggings }).(GetFunctionTriggerLoggingArrayOutput)
}

func (o LookupFunctionTriggerResultOutput) Mails() GetFunctionTriggerMailArrayOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) []GetFunctionTriggerMail { return v.Mails }).(GetFunctionTriggerMailArrayOutput)
}

// [Message Queue](https://cloud.yandex.com/docs/functions/concepts/trigger/ymq-trigger) settings definition for Yandex Cloud Functions Trigger, if present
func (o LookupFunctionTriggerResultOutput) MessageQueues() GetFunctionTriggerMessageQueueArrayOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) []GetFunctionTriggerMessageQueue { return v.MessageQueues }).(GetFunctionTriggerMessageQueueArrayOutput)
}

func (o LookupFunctionTriggerResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// [Object Storage](https://cloud.yandex.com/docs/functions/concepts/trigger/os-trigger) settings definition for Yandex Cloud Functions Trigger, if present
func (o LookupFunctionTriggerResultOutput) ObjectStorages() GetFunctionTriggerObjectStorageArrayOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) []GetFunctionTriggerObjectStorage { return v.ObjectStorages }).(GetFunctionTriggerObjectStorageArrayOutput)
}

// [Timer](https://cloud.yandex.com/docs/functions/concepts/trigger/timer) settings definition for Yandex Cloud Functions Trigger, if present
func (o LookupFunctionTriggerResultOutput) Timers() GetFunctionTriggerTimerArrayOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) []GetFunctionTriggerTimer { return v.Timers }).(GetFunctionTriggerTimerArrayOutput)
}

func (o LookupFunctionTriggerResultOutput) TriggerId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupFunctionTriggerResult) *string { return v.TriggerId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFunctionTriggerResultOutput{})
}
