// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/agorobets/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about SecurityProfile. For more information, see [the official documentation](https://yandex.cloud/docs/smartwebsecurity/concepts/profiles).
//
// This data source is used to define SecurityProfile that can be used by other resources.
//
// ## Example Usage
//
// {{ tffile "examples/sws_security_profile/d_sws_security_profile_1.tf" }}
//
// {{ tffile "examples/sws_security_profile/d_sws_security_profile_2.tf" }}
func LookupSwsSecurityProfile(ctx *pulumi.Context, args *LookupSwsSecurityProfileArgs, opts ...pulumi.InvokeOption) (*LookupSwsSecurityProfileResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSwsSecurityProfileResult
	err := ctx.Invoke("yandex:index/getSwsSecurityProfile:getSwsSecurityProfile", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSwsSecurityProfile.
type LookupSwsSecurityProfileArgs struct {
	CloudId  *string `pulumi:"cloudId"`
	FolderId *string `pulumi:"folderId"`
	// Name of the security profile.
	Name *string `pulumi:"name"`
	// ID of the security profile.
	//
	// > One of `securityProfileId` or `name` should be specified.
	SecurityProfileId *string `pulumi:"securityProfileId"`
}

// A collection of values returned by getSwsSecurityProfile.
type LookupSwsSecurityProfileResult struct {
	// Advanced rate limiter profile ID to use with this security profile. Set empty to use default.
	AdvancedRateLimiterProfileId string `pulumi:"advancedRateLimiterProfileId"`
	// Captcha ID to use with this security profile. Set empty to use default.
	CaptchaId string `pulumi:"captchaId"`
	CloudId   string `pulumi:"cloudId"`
	// The profile creation timestamp.
	CreatedAt string `pulumi:"createdAt"`
	// Action to perform if none of rules matched. Possible values: `ALLOW` or `DENY`.
	DefaultAction string `pulumi:"defaultAction"`
	// Optional description of the rule. 0-512 characters long.
	Description string `pulumi:"description"`
	FolderId    string `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Labels as key:value pairs. Maximum of 64 per resource.
	Labels map[string]string `pulumi:"labels"`
	// Name of the rule. The name is unique within the security profile. 1-50 characters long.
	Name              string  `pulumi:"name"`
	SecurityProfileId *string `pulumi:"securityProfileId"`
	// List of security rules. The structure is documented below.
	SecurityRules []GetSwsSecurityProfileSecurityRule `pulumi:"securityRules"`
}

func LookupSwsSecurityProfileOutput(ctx *pulumi.Context, args LookupSwsSecurityProfileOutputArgs, opts ...pulumi.InvokeOption) LookupSwsSecurityProfileResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupSwsSecurityProfileResultOutput, error) {
			args := v.(LookupSwsSecurityProfileArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getSwsSecurityProfile:getSwsSecurityProfile", args, LookupSwsSecurityProfileResultOutput{}, options).(LookupSwsSecurityProfileResultOutput), nil
		}).(LookupSwsSecurityProfileResultOutput)
}

// A collection of arguments for invoking getSwsSecurityProfile.
type LookupSwsSecurityProfileOutputArgs struct {
	CloudId  pulumi.StringPtrInput `pulumi:"cloudId"`
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	// Name of the security profile.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// ID of the security profile.
	//
	// > One of `securityProfileId` or `name` should be specified.
	SecurityProfileId pulumi.StringPtrInput `pulumi:"securityProfileId"`
}

func (LookupSwsSecurityProfileOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSwsSecurityProfileArgs)(nil)).Elem()
}

// A collection of values returned by getSwsSecurityProfile.
type LookupSwsSecurityProfileResultOutput struct{ *pulumi.OutputState }

func (LookupSwsSecurityProfileResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSwsSecurityProfileResult)(nil)).Elem()
}

func (o LookupSwsSecurityProfileResultOutput) ToLookupSwsSecurityProfileResultOutput() LookupSwsSecurityProfileResultOutput {
	return o
}

func (o LookupSwsSecurityProfileResultOutput) ToLookupSwsSecurityProfileResultOutputWithContext(ctx context.Context) LookupSwsSecurityProfileResultOutput {
	return o
}

// Advanced rate limiter profile ID to use with this security profile. Set empty to use default.
func (o LookupSwsSecurityProfileResultOutput) AdvancedRateLimiterProfileId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.AdvancedRateLimiterProfileId }).(pulumi.StringOutput)
}

// Captcha ID to use with this security profile. Set empty to use default.
func (o LookupSwsSecurityProfileResultOutput) CaptchaId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.CaptchaId }).(pulumi.StringOutput)
}

func (o LookupSwsSecurityProfileResultOutput) CloudId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.CloudId }).(pulumi.StringOutput)
}

// The profile creation timestamp.
func (o LookupSwsSecurityProfileResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Action to perform if none of rules matched. Possible values: `ALLOW` or `DENY`.
func (o LookupSwsSecurityProfileResultOutput) DefaultAction() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.DefaultAction }).(pulumi.StringOutput)
}

// Optional description of the rule. 0-512 characters long.
func (o LookupSwsSecurityProfileResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupSwsSecurityProfileResultOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.FolderId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSwsSecurityProfileResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.Id }).(pulumi.StringOutput)
}

// Labels as key:value pairs. Maximum of 64 per resource.
func (o LookupSwsSecurityProfileResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

// Name of the rule. The name is unique within the security profile. 1-50 characters long.
func (o LookupSwsSecurityProfileResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSwsSecurityProfileResultOutput) SecurityProfileId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) *string { return v.SecurityProfileId }).(pulumi.StringPtrOutput)
}

// List of security rules. The structure is documented below.
func (o LookupSwsSecurityProfileResultOutput) SecurityRules() GetSwsSecurityProfileSecurityRuleArrayOutput {
	return o.ApplyT(func(v LookupSwsSecurityProfileResult) []GetSwsSecurityProfileSecurityRule { return v.SecurityRules }).(GetSwsSecurityProfileSecurityRuleArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSwsSecurityProfileResultOutput{})
}
