// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/agorobets/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Cloud Serverless Container.
//
// ## Example Usage
//
// {{ tffile "examples/serverless_container/d_serverless_container_1.tf" }}
//
// This data source is used to define Yandex Cloud Container that can be used by other resources.
func LookupServerlessContainer(ctx *pulumi.Context, args *LookupServerlessContainerArgs, opts ...pulumi.InvokeOption) (*LookupServerlessContainerResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupServerlessContainerResult
	err := ctx.Invoke("yandex:index/getServerlessContainer:getServerlessContainer", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServerlessContainer.
type LookupServerlessContainerArgs struct {
	// Network access. If specified the revision will be attached to specified network
	Connectivity *GetServerlessContainerConnectivity `pulumi:"connectivity"`
	// Yandex Cloud Serverless Container id used to define container
	ContainerId *string `pulumi:"containerId"`
	// Folder ID for the Yandex Cloud Serverless Container
	//
	// > Either `containerId` or `name` must be specified.
	FolderId *string `pulumi:"folderId"`
	// Mounts for Yandex Cloud Serverless Container
	Mounts []GetServerlessContainerMount `pulumi:"mounts"`
	// Yandex Cloud Serverless Container name used to define container
	Name *string `pulumi:"name"`
	// Runtime for Yandex Cloud Serverless Container
	Runtime *GetServerlessContainerRuntime `pulumi:"runtime"`
	// Secrets for Yandex Cloud Serverless Container
	Secrets []GetServerlessContainerSecret `pulumi:"secrets"`
	// (**DEPRECATED**, use `mounts.0.object_storage` instead) Storage mounts for Yandex Cloud Serverless Container
	//
	// Deprecated: to manage storage_mountss, please switch to using a separate resource type mounts
	StorageMounts []GetServerlessContainerStorageMount `pulumi:"storageMounts"`
}

// A collection of values returned by getServerlessContainer.
type LookupServerlessContainerResult struct {
	// Concurrency of Yandex Cloud Serverless Container
	Concurrency int `pulumi:"concurrency"`
	// Network access. If specified the revision will be attached to specified network
	Connectivity *GetServerlessContainerConnectivity `pulumi:"connectivity"`
	ContainerId  *string                             `pulumi:"containerId"`
	// Core fraction (**0...100**) of the Yandex Cloud Serverless Container
	CoreFraction int `pulumi:"coreFraction"`
	Cores        int `pulumi:"cores"`
	// Creation timestamp of the Yandex Cloud Serverless Container
	CreatedAt string `pulumi:"createdAt"`
	// Description of the Yandex Cloud Serverless Container
	Description string `pulumi:"description"`
	// Execution timeout (duration format) of Yandex Cloud Serverless Container
	ExecutionTimeout string  `pulumi:"executionTimeout"`
	FolderId         *string `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id     string                        `pulumi:"id"`
	Images []GetServerlessContainerImage `pulumi:"images"`
	// A set of key/value label pairs assigned to the Yandex Cloud Serverless Container
	Labels map[string]string `pulumi:"labels"`
	// Options for logging from Yandex Cloud Serverless Container
	LogOptions []GetServerlessContainerLogOption `pulumi:"logOptions"`
	// Memory in megabytes of Yandex Cloud Serverless Container
	Memory int `pulumi:"memory"`
	// Mounts for Yandex Cloud Serverless Container
	Mounts []GetServerlessContainerMount `pulumi:"mounts"`
	Name   *string                       `pulumi:"name"`
	// Last revision ID of the Yandex Cloud Serverless Container
	RevisionId string `pulumi:"revisionId"`
	// Runtime for Yandex Cloud Serverless Container
	Runtime GetServerlessContainerRuntime `pulumi:"runtime"`
	// Secrets for Yandex Cloud Serverless Container
	Secrets []GetServerlessContainerSecret `pulumi:"secrets"`
	// Service account ID of Yandex Cloud Serverless Container
	ServiceAccountId string `pulumi:"serviceAccountId"`
	// (**DEPRECATED**, use `mounts.0.object_storage` instead) Storage mounts for Yandex Cloud Serverless Container
	//
	// Deprecated: to manage storage_mountss, please switch to using a separate resource type mounts
	StorageMounts []GetServerlessContainerStorageMount `pulumi:"storageMounts"`
	// Invoke URL of the Yandex Cloud Serverless Container
	Url string `pulumi:"url"`
}

func LookupServerlessContainerOutput(ctx *pulumi.Context, args LookupServerlessContainerOutputArgs, opts ...pulumi.InvokeOption) LookupServerlessContainerResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupServerlessContainerResultOutput, error) {
			args := v.(LookupServerlessContainerArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getServerlessContainer:getServerlessContainer", args, LookupServerlessContainerResultOutput{}, options).(LookupServerlessContainerResultOutput), nil
		}).(LookupServerlessContainerResultOutput)
}

// A collection of arguments for invoking getServerlessContainer.
type LookupServerlessContainerOutputArgs struct {
	// Network access. If specified the revision will be attached to specified network
	Connectivity GetServerlessContainerConnectivityPtrInput `pulumi:"connectivity"`
	// Yandex Cloud Serverless Container id used to define container
	ContainerId pulumi.StringPtrInput `pulumi:"containerId"`
	// Folder ID for the Yandex Cloud Serverless Container
	//
	// > Either `containerId` or `name` must be specified.
	FolderId pulumi.StringPtrInput `pulumi:"folderId"`
	// Mounts for Yandex Cloud Serverless Container
	Mounts GetServerlessContainerMountArrayInput `pulumi:"mounts"`
	// Yandex Cloud Serverless Container name used to define container
	Name pulumi.StringPtrInput `pulumi:"name"`
	// Runtime for Yandex Cloud Serverless Container
	Runtime GetServerlessContainerRuntimePtrInput `pulumi:"runtime"`
	// Secrets for Yandex Cloud Serverless Container
	Secrets GetServerlessContainerSecretArrayInput `pulumi:"secrets"`
	// (**DEPRECATED**, use `mounts.0.object_storage` instead) Storage mounts for Yandex Cloud Serverless Container
	//
	// Deprecated: to manage storage_mountss, please switch to using a separate resource type mounts
	StorageMounts GetServerlessContainerStorageMountArrayInput `pulumi:"storageMounts"`
}

func (LookupServerlessContainerOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupServerlessContainerArgs)(nil)).Elem()
}

// A collection of values returned by getServerlessContainer.
type LookupServerlessContainerResultOutput struct{ *pulumi.OutputState }

func (LookupServerlessContainerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupServerlessContainerResult)(nil)).Elem()
}

func (o LookupServerlessContainerResultOutput) ToLookupServerlessContainerResultOutput() LookupServerlessContainerResultOutput {
	return o
}

func (o LookupServerlessContainerResultOutput) ToLookupServerlessContainerResultOutputWithContext(ctx context.Context) LookupServerlessContainerResultOutput {
	return o
}

// Concurrency of Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) Concurrency() pulumi.IntOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) int { return v.Concurrency }).(pulumi.IntOutput)
}

// Network access. If specified the revision will be attached to specified network
func (o LookupServerlessContainerResultOutput) Connectivity() GetServerlessContainerConnectivityPtrOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) *GetServerlessContainerConnectivity { return v.Connectivity }).(GetServerlessContainerConnectivityPtrOutput)
}

func (o LookupServerlessContainerResultOutput) ContainerId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) *string { return v.ContainerId }).(pulumi.StringPtrOutput)
}

// Core fraction (**0...100**) of the Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) CoreFraction() pulumi.IntOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) int { return v.CoreFraction }).(pulumi.IntOutput)
}

func (o LookupServerlessContainerResultOutput) Cores() pulumi.IntOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) int { return v.Cores }).(pulumi.IntOutput)
}

// Creation timestamp of the Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Description of the Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.Description }).(pulumi.StringOutput)
}

// Execution timeout (duration format) of Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) ExecutionTimeout() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.ExecutionTimeout }).(pulumi.StringOutput)
}

func (o LookupServerlessContainerResultOutput) FolderId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) *string { return v.FolderId }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupServerlessContainerResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupServerlessContainerResultOutput) Images() GetServerlessContainerImageArrayOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) []GetServerlessContainerImage { return v.Images }).(GetServerlessContainerImageArrayOutput)
}

// A set of key/value label pairs assigned to the Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

// Options for logging from Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) LogOptions() GetServerlessContainerLogOptionArrayOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) []GetServerlessContainerLogOption { return v.LogOptions }).(GetServerlessContainerLogOptionArrayOutput)
}

// Memory in megabytes of Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) Memory() pulumi.IntOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) int { return v.Memory }).(pulumi.IntOutput)
}

// Mounts for Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) Mounts() GetServerlessContainerMountArrayOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) []GetServerlessContainerMount { return v.Mounts }).(GetServerlessContainerMountArrayOutput)
}

func (o LookupServerlessContainerResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// Last revision ID of the Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) RevisionId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.RevisionId }).(pulumi.StringOutput)
}

// Runtime for Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) Runtime() GetServerlessContainerRuntimeOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) GetServerlessContainerRuntime { return v.Runtime }).(GetServerlessContainerRuntimeOutput)
}

// Secrets for Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) Secrets() GetServerlessContainerSecretArrayOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) []GetServerlessContainerSecret { return v.Secrets }).(GetServerlessContainerSecretArrayOutput)
}

// Service account ID of Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) ServiceAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.ServiceAccountId }).(pulumi.StringOutput)
}

// (**DEPRECATED**, use `mounts.0.object_storage` instead) Storage mounts for Yandex Cloud Serverless Container
//
// Deprecated: to manage storage_mountss, please switch to using a separate resource type mounts
func (o LookupServerlessContainerResultOutput) StorageMounts() GetServerlessContainerStorageMountArrayOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) []GetServerlessContainerStorageMount { return v.StorageMounts }).(GetServerlessContainerStorageMountArrayOutput)
}

// Invoke URL of the Yandex Cloud Serverless Container
func (o LookupServerlessContainerResultOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServerlessContainerResult) string { return v.Url }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupServerlessContainerResultOutput{})
}
