// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/agorobets/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates a Captcha in the specified folder. For more information, see [the official documentation](https://yandex.cloud/docs/smartcaptcha/).
//
// ## Example Usage
//
// {{ tffile "examples/smartcaptcha_captcha/r_smartcaptcha_captcha_1.tf" }}
//
// {{ tffile "examples/smartcaptcha_captcha/r_smartcaptcha_captcha_2.tf" }}
//
// ## Import
//
// Resource can be imported using the following syntax:
//
// {{ codefile "shell" "examples/smartcaptcha_captcha/import.sh" }}
type SmartcaptchaCaptcha struct {
	pulumi.CustomResourceState

	// List of allowed host names, see [Domain validation](https://yandex.cloud/docs/smartcaptcha/concepts/domain-validation).
	AllowedSites pulumi.StringArrayOutput `pulumi:"allowedSites"`
	// Additional task type of the captcha. Possible values are documented below.
	ChallengeType pulumi.StringPtrOutput `pulumi:"challengeType"`
	// Client key of the captcha, see [CAPTCHA keys](https://yandex.cloud/docs/smartcaptcha/concepts/keys).
	ClientKey pulumi.StringOutput `pulumi:"clientKey"`
	CloudId   pulumi.StringOutput `pulumi:"cloudId"`
	// Complexity of the captcha. Possible values are documented below.
	Complexity pulumi.StringPtrOutput `pulumi:"complexity"`
	// The Captcha creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Determines whether captcha is protected from being deleted.
	DeletionProtection pulumi.BoolPtrOutput `pulumi:"deletionProtection"`
	// ID of the folder to create a captcha in. If omitted, the provider folder is used.
	FolderId pulumi.StringOutput `pulumi:"folderId"`
	// Name of the captcha. The name must be unique within the folder.
	Name pulumi.StringOutput `pulumi:"name"`
	// List of variants to use in security_rules. The structure is documented below.
	OverrideVariants SmartcaptchaCaptchaOverrideVariantArrayOutput `pulumi:"overrideVariants"`
	// Basic check type of the captcha. Possible values are documented below.
	PreCheckType pulumi.StringPtrOutput `pulumi:"preCheckType"`
	// List of security rules. The structure is documented below.
	SecurityRules SmartcaptchaCaptchaSecurityRuleArrayOutput `pulumi:"securityRules"`
	// JSON with variables to define the captcha appearance. For more details see generated JSON in cloud console.
	StyleJson pulumi.StringPtrOutput `pulumi:"styleJson"`
	Suspend   pulumi.BoolOutput      `pulumi:"suspend"`
	// Turn off host name check, see [Domain validation](https://yandex.cloud/docs/smartcaptcha/concepts/domain-validation).
	TurnOffHostnameCheck pulumi.BoolPtrOutput `pulumi:"turnOffHostnameCheck"`
}

// NewSmartcaptchaCaptcha registers a new resource with the given unique name, arguments, and options.
func NewSmartcaptchaCaptcha(ctx *pulumi.Context,
	name string, args *SmartcaptchaCaptchaArgs, opts ...pulumi.ResourceOption) (*SmartcaptchaCaptcha, error) {
	if args == nil {
		args = &SmartcaptchaCaptchaArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SmartcaptchaCaptcha
	err := ctx.RegisterResource("yandex:index/smartcaptchaCaptcha:SmartcaptchaCaptcha", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSmartcaptchaCaptcha gets an existing SmartcaptchaCaptcha resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSmartcaptchaCaptcha(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SmartcaptchaCaptchaState, opts ...pulumi.ResourceOption) (*SmartcaptchaCaptcha, error) {
	var resource SmartcaptchaCaptcha
	err := ctx.ReadResource("yandex:index/smartcaptchaCaptcha:SmartcaptchaCaptcha", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SmartcaptchaCaptcha resources.
type smartcaptchaCaptchaState struct {
	// List of allowed host names, see [Domain validation](https://yandex.cloud/docs/smartcaptcha/concepts/domain-validation).
	AllowedSites []string `pulumi:"allowedSites"`
	// Additional task type of the captcha. Possible values are documented below.
	ChallengeType *string `pulumi:"challengeType"`
	// Client key of the captcha, see [CAPTCHA keys](https://yandex.cloud/docs/smartcaptcha/concepts/keys).
	ClientKey *string `pulumi:"clientKey"`
	CloudId   *string `pulumi:"cloudId"`
	// Complexity of the captcha. Possible values are documented below.
	Complexity *string `pulumi:"complexity"`
	// The Captcha creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Determines whether captcha is protected from being deleted.
	DeletionProtection *bool `pulumi:"deletionProtection"`
	// ID of the folder to create a captcha in. If omitted, the provider folder is used.
	FolderId *string `pulumi:"folderId"`
	// Name of the captcha. The name must be unique within the folder.
	Name *string `pulumi:"name"`
	// List of variants to use in security_rules. The structure is documented below.
	OverrideVariants []SmartcaptchaCaptchaOverrideVariant `pulumi:"overrideVariants"`
	// Basic check type of the captcha. Possible values are documented below.
	PreCheckType *string `pulumi:"preCheckType"`
	// List of security rules. The structure is documented below.
	SecurityRules []SmartcaptchaCaptchaSecurityRule `pulumi:"securityRules"`
	// JSON with variables to define the captcha appearance. For more details see generated JSON in cloud console.
	StyleJson *string `pulumi:"styleJson"`
	Suspend   *bool   `pulumi:"suspend"`
	// Turn off host name check, see [Domain validation](https://yandex.cloud/docs/smartcaptcha/concepts/domain-validation).
	TurnOffHostnameCheck *bool `pulumi:"turnOffHostnameCheck"`
}

type SmartcaptchaCaptchaState struct {
	// List of allowed host names, see [Domain validation](https://yandex.cloud/docs/smartcaptcha/concepts/domain-validation).
	AllowedSites pulumi.StringArrayInput
	// Additional task type of the captcha. Possible values are documented below.
	ChallengeType pulumi.StringPtrInput
	// Client key of the captcha, see [CAPTCHA keys](https://yandex.cloud/docs/smartcaptcha/concepts/keys).
	ClientKey pulumi.StringPtrInput
	CloudId   pulumi.StringPtrInput
	// Complexity of the captcha. Possible values are documented below.
	Complexity pulumi.StringPtrInput
	// The Captcha creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Determines whether captcha is protected from being deleted.
	DeletionProtection pulumi.BoolPtrInput
	// ID of the folder to create a captcha in. If omitted, the provider folder is used.
	FolderId pulumi.StringPtrInput
	// Name of the captcha. The name must be unique within the folder.
	Name pulumi.StringPtrInput
	// List of variants to use in security_rules. The structure is documented below.
	OverrideVariants SmartcaptchaCaptchaOverrideVariantArrayInput
	// Basic check type of the captcha. Possible values are documented below.
	PreCheckType pulumi.StringPtrInput
	// List of security rules. The structure is documented below.
	SecurityRules SmartcaptchaCaptchaSecurityRuleArrayInput
	// JSON with variables to define the captcha appearance. For more details see generated JSON in cloud console.
	StyleJson pulumi.StringPtrInput
	Suspend   pulumi.BoolPtrInput
	// Turn off host name check, see [Domain validation](https://yandex.cloud/docs/smartcaptcha/concepts/domain-validation).
	TurnOffHostnameCheck pulumi.BoolPtrInput
}

func (SmartcaptchaCaptchaState) ElementType() reflect.Type {
	return reflect.TypeOf((*smartcaptchaCaptchaState)(nil)).Elem()
}

type smartcaptchaCaptchaArgs struct {
	// List of allowed host names, see [Domain validation](https://yandex.cloud/docs/smartcaptcha/concepts/domain-validation).
	AllowedSites []string `pulumi:"allowedSites"`
	// Additional task type of the captcha. Possible values are documented below.
	ChallengeType *string `pulumi:"challengeType"`
	CloudId       *string `pulumi:"cloudId"`
	// Complexity of the captcha. Possible values are documented below.
	Complexity *string `pulumi:"complexity"`
	// Determines whether captcha is protected from being deleted.
	DeletionProtection *bool `pulumi:"deletionProtection"`
	// ID of the folder to create a captcha in. If omitted, the provider folder is used.
	FolderId *string `pulumi:"folderId"`
	// Name of the captcha. The name must be unique within the folder.
	Name *string `pulumi:"name"`
	// List of variants to use in security_rules. The structure is documented below.
	OverrideVariants []SmartcaptchaCaptchaOverrideVariant `pulumi:"overrideVariants"`
	// Basic check type of the captcha. Possible values are documented below.
	PreCheckType *string `pulumi:"preCheckType"`
	// List of security rules. The structure is documented below.
	SecurityRules []SmartcaptchaCaptchaSecurityRule `pulumi:"securityRules"`
	// JSON with variables to define the captcha appearance. For more details see generated JSON in cloud console.
	StyleJson *string `pulumi:"styleJson"`
	// Turn off host name check, see [Domain validation](https://yandex.cloud/docs/smartcaptcha/concepts/domain-validation).
	TurnOffHostnameCheck *bool `pulumi:"turnOffHostnameCheck"`
}

// The set of arguments for constructing a SmartcaptchaCaptcha resource.
type SmartcaptchaCaptchaArgs struct {
	// List of allowed host names, see [Domain validation](https://yandex.cloud/docs/smartcaptcha/concepts/domain-validation).
	AllowedSites pulumi.StringArrayInput
	// Additional task type of the captcha. Possible values are documented below.
	ChallengeType pulumi.StringPtrInput
	CloudId       pulumi.StringPtrInput
	// Complexity of the captcha. Possible values are documented below.
	Complexity pulumi.StringPtrInput
	// Determines whether captcha is protected from being deleted.
	DeletionProtection pulumi.BoolPtrInput
	// ID of the folder to create a captcha in. If omitted, the provider folder is used.
	FolderId pulumi.StringPtrInput
	// Name of the captcha. The name must be unique within the folder.
	Name pulumi.StringPtrInput
	// List of variants to use in security_rules. The structure is documented below.
	OverrideVariants SmartcaptchaCaptchaOverrideVariantArrayInput
	// Basic check type of the captcha. Possible values are documented below.
	PreCheckType pulumi.StringPtrInput
	// List of security rules. The structure is documented below.
	SecurityRules SmartcaptchaCaptchaSecurityRuleArrayInput
	// JSON with variables to define the captcha appearance. For more details see generated JSON in cloud console.
	StyleJson pulumi.StringPtrInput
	// Turn off host name check, see [Domain validation](https://yandex.cloud/docs/smartcaptcha/concepts/domain-validation).
	TurnOffHostnameCheck pulumi.BoolPtrInput
}

func (SmartcaptchaCaptchaArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*smartcaptchaCaptchaArgs)(nil)).Elem()
}

type SmartcaptchaCaptchaInput interface {
	pulumi.Input

	ToSmartcaptchaCaptchaOutput() SmartcaptchaCaptchaOutput
	ToSmartcaptchaCaptchaOutputWithContext(ctx context.Context) SmartcaptchaCaptchaOutput
}

func (*SmartcaptchaCaptcha) ElementType() reflect.Type {
	return reflect.TypeOf((**SmartcaptchaCaptcha)(nil)).Elem()
}

func (i *SmartcaptchaCaptcha) ToSmartcaptchaCaptchaOutput() SmartcaptchaCaptchaOutput {
	return i.ToSmartcaptchaCaptchaOutputWithContext(context.Background())
}

func (i *SmartcaptchaCaptcha) ToSmartcaptchaCaptchaOutputWithContext(ctx context.Context) SmartcaptchaCaptchaOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmartcaptchaCaptchaOutput)
}

// SmartcaptchaCaptchaArrayInput is an input type that accepts SmartcaptchaCaptchaArray and SmartcaptchaCaptchaArrayOutput values.
// You can construct a concrete instance of `SmartcaptchaCaptchaArrayInput` via:
//
//	SmartcaptchaCaptchaArray{ SmartcaptchaCaptchaArgs{...} }
type SmartcaptchaCaptchaArrayInput interface {
	pulumi.Input

	ToSmartcaptchaCaptchaArrayOutput() SmartcaptchaCaptchaArrayOutput
	ToSmartcaptchaCaptchaArrayOutputWithContext(context.Context) SmartcaptchaCaptchaArrayOutput
}

type SmartcaptchaCaptchaArray []SmartcaptchaCaptchaInput

func (SmartcaptchaCaptchaArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SmartcaptchaCaptcha)(nil)).Elem()
}

func (i SmartcaptchaCaptchaArray) ToSmartcaptchaCaptchaArrayOutput() SmartcaptchaCaptchaArrayOutput {
	return i.ToSmartcaptchaCaptchaArrayOutputWithContext(context.Background())
}

func (i SmartcaptchaCaptchaArray) ToSmartcaptchaCaptchaArrayOutputWithContext(ctx context.Context) SmartcaptchaCaptchaArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmartcaptchaCaptchaArrayOutput)
}

// SmartcaptchaCaptchaMapInput is an input type that accepts SmartcaptchaCaptchaMap and SmartcaptchaCaptchaMapOutput values.
// You can construct a concrete instance of `SmartcaptchaCaptchaMapInput` via:
//
//	SmartcaptchaCaptchaMap{ "key": SmartcaptchaCaptchaArgs{...} }
type SmartcaptchaCaptchaMapInput interface {
	pulumi.Input

	ToSmartcaptchaCaptchaMapOutput() SmartcaptchaCaptchaMapOutput
	ToSmartcaptchaCaptchaMapOutputWithContext(context.Context) SmartcaptchaCaptchaMapOutput
}

type SmartcaptchaCaptchaMap map[string]SmartcaptchaCaptchaInput

func (SmartcaptchaCaptchaMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SmartcaptchaCaptcha)(nil)).Elem()
}

func (i SmartcaptchaCaptchaMap) ToSmartcaptchaCaptchaMapOutput() SmartcaptchaCaptchaMapOutput {
	return i.ToSmartcaptchaCaptchaMapOutputWithContext(context.Background())
}

func (i SmartcaptchaCaptchaMap) ToSmartcaptchaCaptchaMapOutputWithContext(ctx context.Context) SmartcaptchaCaptchaMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmartcaptchaCaptchaMapOutput)
}

type SmartcaptchaCaptchaOutput struct{ *pulumi.OutputState }

func (SmartcaptchaCaptchaOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SmartcaptchaCaptcha)(nil)).Elem()
}

func (o SmartcaptchaCaptchaOutput) ToSmartcaptchaCaptchaOutput() SmartcaptchaCaptchaOutput {
	return o
}

func (o SmartcaptchaCaptchaOutput) ToSmartcaptchaCaptchaOutputWithContext(ctx context.Context) SmartcaptchaCaptchaOutput {
	return o
}

// List of allowed host names, see [Domain validation](https://yandex.cloud/docs/smartcaptcha/concepts/domain-validation).
func (o SmartcaptchaCaptchaOutput) AllowedSites() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) pulumi.StringArrayOutput { return v.AllowedSites }).(pulumi.StringArrayOutput)
}

// Additional task type of the captcha. Possible values are documented below.
func (o SmartcaptchaCaptchaOutput) ChallengeType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) pulumi.StringPtrOutput { return v.ChallengeType }).(pulumi.StringPtrOutput)
}

// Client key of the captcha, see [CAPTCHA keys](https://yandex.cloud/docs/smartcaptcha/concepts/keys).
func (o SmartcaptchaCaptchaOutput) ClientKey() pulumi.StringOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) pulumi.StringOutput { return v.ClientKey }).(pulumi.StringOutput)
}

func (o SmartcaptchaCaptchaOutput) CloudId() pulumi.StringOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) pulumi.StringOutput { return v.CloudId }).(pulumi.StringOutput)
}

// Complexity of the captcha. Possible values are documented below.
func (o SmartcaptchaCaptchaOutput) Complexity() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) pulumi.StringPtrOutput { return v.Complexity }).(pulumi.StringPtrOutput)
}

// The Captcha creation timestamp.
func (o SmartcaptchaCaptchaOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Determines whether captcha is protected from being deleted.
func (o SmartcaptchaCaptchaOutput) DeletionProtection() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) pulumi.BoolPtrOutput { return v.DeletionProtection }).(pulumi.BoolPtrOutput)
}

// ID of the folder to create a captcha in. If omitted, the provider folder is used.
func (o SmartcaptchaCaptchaOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) pulumi.StringOutput { return v.FolderId }).(pulumi.StringOutput)
}

// Name of the captcha. The name must be unique within the folder.
func (o SmartcaptchaCaptchaOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// List of variants to use in security_rules. The structure is documented below.
func (o SmartcaptchaCaptchaOutput) OverrideVariants() SmartcaptchaCaptchaOverrideVariantArrayOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) SmartcaptchaCaptchaOverrideVariantArrayOutput { return v.OverrideVariants }).(SmartcaptchaCaptchaOverrideVariantArrayOutput)
}

// Basic check type of the captcha. Possible values are documented below.
func (o SmartcaptchaCaptchaOutput) PreCheckType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) pulumi.StringPtrOutput { return v.PreCheckType }).(pulumi.StringPtrOutput)
}

// List of security rules. The structure is documented below.
func (o SmartcaptchaCaptchaOutput) SecurityRules() SmartcaptchaCaptchaSecurityRuleArrayOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) SmartcaptchaCaptchaSecurityRuleArrayOutput { return v.SecurityRules }).(SmartcaptchaCaptchaSecurityRuleArrayOutput)
}

// JSON with variables to define the captcha appearance. For more details see generated JSON in cloud console.
func (o SmartcaptchaCaptchaOutput) StyleJson() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) pulumi.StringPtrOutput { return v.StyleJson }).(pulumi.StringPtrOutput)
}

func (o SmartcaptchaCaptchaOutput) Suspend() pulumi.BoolOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) pulumi.BoolOutput { return v.Suspend }).(pulumi.BoolOutput)
}

// Turn off host name check, see [Domain validation](https://yandex.cloud/docs/smartcaptcha/concepts/domain-validation).
func (o SmartcaptchaCaptchaOutput) TurnOffHostnameCheck() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SmartcaptchaCaptcha) pulumi.BoolPtrOutput { return v.TurnOffHostnameCheck }).(pulumi.BoolPtrOutput)
}

type SmartcaptchaCaptchaArrayOutput struct{ *pulumi.OutputState }

func (SmartcaptchaCaptchaArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SmartcaptchaCaptcha)(nil)).Elem()
}

func (o SmartcaptchaCaptchaArrayOutput) ToSmartcaptchaCaptchaArrayOutput() SmartcaptchaCaptchaArrayOutput {
	return o
}

func (o SmartcaptchaCaptchaArrayOutput) ToSmartcaptchaCaptchaArrayOutputWithContext(ctx context.Context) SmartcaptchaCaptchaArrayOutput {
	return o
}

func (o SmartcaptchaCaptchaArrayOutput) Index(i pulumi.IntInput) SmartcaptchaCaptchaOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SmartcaptchaCaptcha {
		return vs[0].([]*SmartcaptchaCaptcha)[vs[1].(int)]
	}).(SmartcaptchaCaptchaOutput)
}

type SmartcaptchaCaptchaMapOutput struct{ *pulumi.OutputState }

func (SmartcaptchaCaptchaMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SmartcaptchaCaptcha)(nil)).Elem()
}

func (o SmartcaptchaCaptchaMapOutput) ToSmartcaptchaCaptchaMapOutput() SmartcaptchaCaptchaMapOutput {
	return o
}

func (o SmartcaptchaCaptchaMapOutput) ToSmartcaptchaCaptchaMapOutputWithContext(ctx context.Context) SmartcaptchaCaptchaMapOutput {
	return o
}

func (o SmartcaptchaCaptchaMapOutput) MapIndex(k pulumi.StringInput) SmartcaptchaCaptchaOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SmartcaptchaCaptcha {
		return vs[0].(map[string]*SmartcaptchaCaptcha)[vs[1].(string)]
	}).(SmartcaptchaCaptchaOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SmartcaptchaCaptchaInput)(nil)).Elem(), &SmartcaptchaCaptcha{})
	pulumi.RegisterInputType(reflect.TypeOf((*SmartcaptchaCaptchaArrayInput)(nil)).Elem(), SmartcaptchaCaptchaArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SmartcaptchaCaptchaMapInput)(nil)).Elem(), SmartcaptchaCaptchaMap{})
	pulumi.RegisterOutputType(SmartcaptchaCaptchaOutput{})
	pulumi.RegisterOutputType(SmartcaptchaCaptchaArrayOutput{})
	pulumi.RegisterOutputType(SmartcaptchaCaptchaMapOutput{})
}
