// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetAuditTrailsTrailFilterPathFilterSomeFilterResult
    {
        /// <summary>
        /// List of child resources from which events will be gathered.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAuditTrailsTrailFilterPathFilterSomeFilterAnyFilterResult> AnyFilters;
        /// <summary>
        /// ID of the monitored resource.
        /// </summary>
        public readonly string ResourceId;
        /// <summary>
        /// Resource type of the monitored resource.
        /// </summary>
        public readonly string ResourceType;

        [OutputConstructor]
        private GetAuditTrailsTrailFilterPathFilterSomeFilterResult(
            ImmutableArray<Outputs.GetAuditTrailsTrailFilterPathFilterSomeFilterAnyFilterResult> anyFilters,

            string resourceId,

            string resourceType)
        {
            AnyFilters = anyFilters;
            ResourceId = resourceId;
            ResourceType = resourceType;
        }
    }
}
