// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetAuditTrailsTrailFilterPathFilterResult
    {
        /// <summary>
        /// Structure describing that events will be gathered from all cloud resources that belong to the parent resource. Mutually exclusive with `some_filter`.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAuditTrailsTrailFilterPathFilterAnyFilterResult> AnyFilters;
        /// <summary>
        /// Structure describing that events will be gathered from some of the cloud resources that belong to the parent resource. Mutually exclusive with `any_filter`.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAuditTrailsTrailFilterPathFilterSomeFilterResult> SomeFilters;

        [OutputConstructor]
        private GetAuditTrailsTrailFilterPathFilterResult(
            ImmutableArray<Outputs.GetAuditTrailsTrailFilterPathFilterAnyFilterResult> anyFilters,

            ImmutableArray<Outputs.GetAuditTrailsTrailFilterPathFilterSomeFilterResult> someFilters)
        {
            AnyFilters = anyFilters;
            SomeFilters = someFilters;
        }
    }
}
