// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetAuditTrailsTrailFilteringPolicyDataEventsFilterResult
    {
        /// <summary>
        /// (Optional) A list of events that won't be gathered by the trail from this service. New events will be automatically gathered when this option is specified. Mutually exclusive with `included_events`
        /// </summary>
        public readonly ImmutableArray<string> ExcludedEvents;
        /// <summary>
        /// (Optional) A list of events that will be gathered by the trail from this service. New events won't be gathered by default when this option is specified. Mutually exclusive with `excluded_events`
        /// </summary>
        public readonly ImmutableArray<string> IncludedEvents;
        /// <summary>
        /// Structure describing that events will be gathered from the specified resource.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAuditTrailsTrailFilteringPolicyDataEventsFilterResourceScopeResult> ResourceScopes;
        /// <summary>
        /// ID of the service which events will be gathered.
        /// </summary>
        public readonly string Service;

        [OutputConstructor]
        private GetAuditTrailsTrailFilteringPolicyDataEventsFilterResult(
            ImmutableArray<string> excludedEvents,

            ImmutableArray<string> includedEvents,

            ImmutableArray<Outputs.GetAuditTrailsTrailFilteringPolicyDataEventsFilterResourceScopeResult> resourceScopes,

            string service)
        {
            ExcludedEvents = excludedEvents;
            IncludedEvents = includedEvents;
            ResourceScopes = resourceScopes;
            Service = service;
        }
    }
}
