// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetComputeInstanceHardwareGenerationResult
    {
        /// <summary>
        /// A newer hardware generation, which always uses `PCI_TOPOLOGY_V2` and UEFI boot.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetComputeInstanceHardwareGenerationGeneration2FeatureResult> Generation2Features;
        /// <summary>
        /// Defines the first known hardware generation and its features, which are:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetComputeInstanceHardwareGenerationLegacyFeatureResult> LegacyFeatures;

        [OutputConstructor]
        private GetComputeInstanceHardwareGenerationResult(
            ImmutableArray<Outputs.GetComputeInstanceHardwareGenerationGeneration2FeatureResult> generation2Features,

            ImmutableArray<Outputs.GetComputeInstanceHardwareGenerationLegacyFeatureResult> legacyFeatures)
        {
            Generation2Features = generation2Features;
            LegacyFeatures = legacyFeatures;
        }
    }
}
