// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetFunctionMountResult
    {
        /// <summary>
        /// One of the available mount types. Disk available during the function execution time
        /// </summary>
        public readonly Outputs.GetFunctionMountEphemeralDiskResult? EphemeralDisk;
        /// <summary>
        /// Mount’s accessibility mode. Valid values are `ro` and `rw`
        /// </summary>
        public readonly string Mode;
        /// <summary>
        /// Yandex Cloud Function name used to define function
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// One of the available mount types. Object storage as a mount
        /// </summary>
        public readonly Outputs.GetFunctionMountObjectStorageResult? ObjectStorage;

        [OutputConstructor]
        private GetFunctionMountResult(
            Outputs.GetFunctionMountEphemeralDiskResult? ephemeralDisk,

            string mode,

            string name,

            Outputs.GetFunctionMountObjectStorageResult? objectStorage)
        {
            EphemeralDisk = ephemeralDisk;
            Mode = mode;
            Name = name;
            ObjectStorage = objectStorage;
        }
    }
}
