// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetLbNetworkLoadBalancerAttachedTargetGroupHealthcheckResult
    {
        /// <summary>
        /// Number of successful health checks required in order to set the `HEALTHY` status for the target.
        /// </summary>
        public readonly int HealthyThreshold;
        public readonly ImmutableArray<Outputs.GetLbNetworkLoadBalancerAttachedTargetGroupHealthcheckHttpOptionResult> HttpOptions;
        /// <summary>
        /// The interval between health checks.
        /// </summary>
        public readonly int Interval;
        /// <summary>
        /// Name of the network load balancer.
        /// 
        /// &gt; One of `network_load_balancer_id` or `name` should be specified.
        /// </summary>
        public readonly string Name;
        public readonly ImmutableArray<Outputs.GetLbNetworkLoadBalancerAttachedTargetGroupHealthcheckTcpOptionResult> TcpOptions;
        /// <summary>
        /// Timeout for a target to return a response for the health check.
        /// </summary>
        public readonly int Timeout;
        /// <summary>
        /// Number of failed health checks before changing the status to `UNHEALTHY`.
        /// </summary>
        public readonly int UnhealthyThreshold;

        [OutputConstructor]
        private GetLbNetworkLoadBalancerAttachedTargetGroupHealthcheckResult(
            int healthyThreshold,

            ImmutableArray<Outputs.GetLbNetworkLoadBalancerAttachedTargetGroupHealthcheckHttpOptionResult> httpOptions,

            int interval,

            string name,

            ImmutableArray<Outputs.GetLbNetworkLoadBalancerAttachedTargetGroupHealthcheckTcpOptionResult> tcpOptions,

            int timeout,

            int unhealthyThreshold)
        {
            HealthyThreshold = healthyThreshold;
            HttpOptions = httpOptions;
            Interval = interval;
            Name = name;
            TcpOptions = tcpOptions;
            Timeout = timeout;
            UnhealthyThreshold = unhealthyThreshold;
        }
    }
}
