// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetMdbKafkaClusterConfigKraftResourcesResult
    {
        /// <summary>
        /// (Optional) Volume of the storage available to a KRaft-controller host, in gigabytes.
        /// </summary>
        public readonly int DiskSize;
        /// <summary>
        /// (Optional) Type of the storage of KRaft-controller hosts. For more information see [the official documentation](https://cloud.yandex.com/docs/managed-kafka/concepts/storage).
        /// </summary>
        public readonly string DiskTypeId;
        public readonly string ResourcePresetId;

        [OutputConstructor]
        private GetMdbKafkaClusterConfigKraftResourcesResult(
            int diskSize,

            string diskTypeId,

            string resourcePresetId)
        {
            DiskSize = diskSize;
            DiskTypeId = diskTypeId;
            ResourcePresetId = resourcePresetId;
        }
    }
}
