// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetSwsAdvancedRateLimiterProfileAdvancedRateLimiterRuleStaticQuotaConditionHeaderResult
    {
        /// <summary>
        /// Name of the ARL profile.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// String value of the key.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSwsAdvancedRateLimiterProfileAdvancedRateLimiterRuleStaticQuotaConditionHeaderValueResult> Values;

        [OutputConstructor]
        private GetSwsAdvancedRateLimiterProfileAdvancedRateLimiterRuleStaticQuotaConditionHeaderResult(
            string name,

            ImmutableArray<Outputs.GetSwsAdvancedRateLimiterProfileAdvancedRateLimiterRuleStaticQuotaConditionHeaderValueResult> values)
        {
            Name = name;
            Values = values;
        }
    }
}
