// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class SwsAdvancedRateLimiterProfileAdvancedRateLimiterRuleDynamicQuotaCharacteristic
    {
        /// <summary>
        /// Determines case-sensitive or case-insensitive keys matching.
        /// 
        /// &gt; Exactly one characteristic specifier: `simple_characteristic` or `key_characteristic` should be specified.
        /// </summary>
        public readonly bool? CaseInsensitive;
        /// <summary>
        /// Characteristic based on key match in the Query params, HTTP header, and HTTP cookie attributes. See [Rules](https://yandex.cloud/en/docs/smartwebsecurity/concepts/arl#requests-counting) for more details. The structure is documented below.
        /// </summary>
        public readonly Outputs.SwsAdvancedRateLimiterProfileAdvancedRateLimiterRuleDynamicQuotaCharacteristicKeyCharacteristic? KeyCharacteristic;
        /// <summary>
        /// Characteristic automatically based on the Request path, HTTP method, IP address, Region, and Host attributes. See [Rules](https://yandex.cloud/en/docs/smartwebsecurity/concepts/arl#requests-counting) for more details. The structure is documented below.
        /// </summary>
        public readonly Outputs.SwsAdvancedRateLimiterProfileAdvancedRateLimiterRuleDynamicQuotaCharacteristicSimpleCharacteristic? SimpleCharacteristic;

        [OutputConstructor]
        private SwsAdvancedRateLimiterProfileAdvancedRateLimiterRuleDynamicQuotaCharacteristic(
            bool? caseInsensitive,

            Outputs.SwsAdvancedRateLimiterProfileAdvancedRateLimiterRuleDynamicQuotaCharacteristicKeyCharacteristic? keyCharacteristic,

            Outputs.SwsAdvancedRateLimiterProfileAdvancedRateLimiterRuleDynamicQuotaCharacteristicSimpleCharacteristic? simpleCharacteristic)
        {
            CaseInsensitive = caseInsensitive;
            KeyCharacteristic = keyCharacteristic;
            SimpleCharacteristic = simpleCharacteristic;
        }
    }
}
