// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class SwsSecurityProfileSecurityRuleWafConditionHeader
    {
        /// <summary>
        /// Name of the security profile. The name is unique within the folder. 1-50 characters long.
        /// </summary>
        public readonly string? Name;
        public readonly Outputs.SwsSecurityProfileSecurityRuleWafConditionHeaderValue Value;

        [OutputConstructor]
        private SwsSecurityProfileSecurityRuleWafConditionHeader(
            string? name,

            Outputs.SwsSecurityProfileSecurityRuleWafConditionHeaderValue value)
        {
            Name = name;
            Value = value;
        }
    }
}
