// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class FunctionMountGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("ephemeralDisk")]
        public Input<Inputs.FunctionMountEphemeralDiskGetArgs>? EphemeralDisk { get; set; }

        [Input("mode")]
        public Input<string>? Mode { get; set; }

        /// <summary>
        /// Yandex Cloud Function name used to define trigger
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("objectStorage")]
        public Input<Inputs.FunctionMountObjectStorageGetArgs>? ObjectStorage { get; set; }

        public FunctionMountGetArgs()
        {
        }
        public static new FunctionMountGetArgs Empty => new FunctionMountGetArgs();
    }
}
